/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ Ą │ Č │ Ę │ Ė │ Į │ Š │ Ų │ Ū │ 9 │ 0 │ - │ Ž │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ [ │ ] │  \  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ; │ ' │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ / │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '~\n`', title: 'LT_GRV' },
  KC_1: { name: 'Ą', title: 'LT_AOGO' },
  KC_2: { name: 'Č', title: 'LT_CCAR' },
  KC_3: { name: 'Ę', title: 'LT_EOGO' },
  KC_4: { name: 'Ė', title: 'LT_EDOT' },
  KC_5: { name: 'Į', title: 'LT_IOGO' },
  KC_6: { name: 'Š', title: 'LT_SCAR' },
  KC_7: { name: 'Ų', title: 'LT_UOGO' },
  KC_8: { name: 'Ū', title: 'LT_UMAC' },
  KC_9: { name: '(\n9', title: 'LT_9' },
  KC_0: { name: ')\n0', title: 'LT_0' },
  KC_MINS: { name: '_\n-', title: 'LT_MINS' },
  KC_EQL: { name: 'Ž', title: 'LT_ZCAR' },
  // Row 2
  KC_Q: { name: 'Q', title: 'LT_Q' },
  KC_W: { name: 'W', title: 'LT_W' },
  KC_E: { name: 'E', title: 'LT_E' },
  KC_R: { name: 'R', title: 'LT_R' },
  KC_T: { name: 'T', title: 'LT_T' },
  KC_Y: { name: 'Y', title: 'LT_Y' },
  KC_U: { name: 'U', title: 'LT_U' },
  KC_I: { name: 'I', title: 'LT_I' },
  KC_O: { name: 'O', title: 'LT_O' },
  KC_P: { name: 'P', title: 'LT_P' },
  KC_LBRC: { name: '{\n[', title: 'LT_LBRC' },
  KC_RBRC: { name: '}\n]', title: 'LT_RBRC' },
  // Row 3
  KC_A: { name: 'A', title: 'LT_A' },
  KC_S: { name: 'S', title: 'LT_S' },
  KC_D: { name: 'D', title: 'LT_D' },
  KC_F: { name: 'F', title: 'LT_F' },
  KC_G: { name: 'G', title: 'LT_G' },
  KC_H: { name: 'H', title: 'LT_H' },
  KC_J: { name: 'J', title: 'LT_J' },
  KC_K: { name: 'K', title: 'LT_K' },
  KC_L: { name: 'L', title: 'LT_L' },
  KC_SCLN: { name: ':\n;', title: 'LT_SCLN' },
  KC_QUOT: { name: '"\n\'', title: 'LT_QUOT' },
  KC_BSLS: { name: '|\n\\', title: 'LT_BSLS' },
  // Row 4
  KC_Z: { name: 'Z', title: 'LT_Z' },
  KC_X: { name: 'X', title: 'LT_X' },
  KC_C: { name: 'C', title: 'LT_C' },
  KC_V: { name: 'V', title: 'LT_V' },
  KC_B: { name: 'B', title: 'LT_B' },
  KC_N: { name: 'N', title: 'LT_N' },
  KC_M: { name: 'M', title: 'LT_M' },
  KC_COMM: { name: '<\n,', title: 'LT_COMM' },
  KC_DOT: { name: '>\n.', title: 'LT_DOT' },
  KC_SLSH: { name: '?\n/', title: 'LT_SLSH' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │   │   │   │   │   │   │   │   │ ( │ ) │ _ │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ { │ } │  |  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │   │   │   │   │   │   │   │   │   │ : │ " │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │   │   │   │   │   │   │   │ < │ > │ ? │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', title: 'LT_TILD' },
  KC_TILD: { name: '~', title: 'LT_TILD' },
  'S(KC_9)': { name: '(', title: 'LT_LPRN' },
  KC_LPRN: { name: '(', title: 'LT_LPRN' },
  'S(KC_0)': { name: ')', title: 'LT_RPRN' },
  KC_RPRN: { name: ')', title: 'LT_RPRN' },
  'S(KC_MINS)': { name: '_', title: 'LT_UNDS' },
  KC_UNDS: { name: '_', title: 'LT_UNDS' },
  // Row 2
  'S(KC_LBRC)': { name: '{', title: 'LT_LCBR' },
  KC_LCBR: { name: '{', title: 'LT_LCBR' },
  'S(KC_RBRC)': { name: '}', title: 'LT_RCBR' },
  KC_RCBR: { name: '}', title: 'LT_RCBR' },
  // Row 3
  'S(KC_SCLN)': { name: ':', title: 'LT_COLN' },
  KC_COLN: { name: ':', title: 'LT_COLN' },
  'S(KC_QUOT)': { name: '"', title: 'LT_DQUO' },
  KC_DQUO: { name: '"', title: 'LT_DQUO' },
  'S(KC_BSLS)': { name: '|', title: 'LT_PIPE' },
  KC_PIPE: { name: '|', title: 'LT_PIPE' },
  // Row 4
  'S(KC_COMM)': { name: '<', title: 'LT_LABK' },
  KC_LT: { name: '<', title: 'LT_LABK' },
  'S(KC_DOT)': { name: '>', title: 'LT_RABK' },
  KC_GT: { name: '>', title: 'LT_RABK' },
  'S(KC_SLSH)': { name: '?', title: 'LT_QUES' },
  KC_QUES: { name: '?', title: 'LT_QUES' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │   │   │   │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ € │   │   │   │   │   │   │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │   │   │   │   │   │   │   │   │   │   │   │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_1)': { name: '1', title: 'LT_1' },
  'ALGR(KC_2)': { name: '2', title: 'LT_2' },
  'ALGR(KC_3)': { name: '3', title: 'LT_3' },
  'ALGR(KC_4)': { name: '4', title: 'LT_4' },
  'ALGR(KC_5)': { name: '5', title: 'LT_5' },
  'ALGR(KC_6)': { name: '6', title: 'LT_6' },
  'ALGR(KC_7)': { name: '7', title: 'LT_7' },
  'ALGR(KC_8)': { name: '8', title: 'LT_8' },
  'ALGR(KC_EQL)': { name: '=', title: 'LT_EQL' },
  // Row 2
  'ALGR(KC_E)': { name: '€', title: 'LT_EURO' },

  /* Shift+AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │ ! │ @ │ # │ $ │ % │ ^ │ & │ * │   │   │   │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │   │   │   │   │   │   │   │   │   │   │   │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(ALGR(KC_1))': { name: '!', title: 'LT_EXLM' },
  'S(ALGR(KC_2))': { name: '@', title: 'LT_AT' },
  'S(ALGR(KC_3))': { name: '#', title: 'LT_HASH' },
  'S(ALGR(KC_4))': { name: '$', title: 'LT_DLR' },
  'S(ALGR(KC_5))': { name: '%', title: 'LT_PERC' },
  'S(ALGR(KC_6))': { name: '^', title: 'LT_CIRC' },
  'S(ALGR(KC_7))': { name: '&', title: 'LT_AMPR' },
  'S(ALGR(KC_8))': { name: '*', title: 'LT_ASTR' },
  'S(ALGR(KC_EQL))': { name: '+', title: 'LT_PLUS' },

  /* Other keys */
  KC_NUHS: { name: '|\n\\', title: '' },
  'S(KC_NUHS)': { name: '|', title: '' },
  KC_NUBS: { name: '|\n\\', title: '' },
  'S(KC_NUBS)': { name: '|', title: '' },
  KC_EXLM: { name: 'Ą', title: 'S(LT_AOGO) (capital Ą)' },
  KC_AT: { name: 'Č', title: 'S(LT_CCAR) (capital Č)' },
  KC_HASH: { name: 'Ę', title: 'S(LT_EOGO) (capital Ę)' },
  KC_DLR: { name: 'Ė', title: 'S(LT_EDOT) (capital Ė)' },
  KC_PERC: { name: 'Į', title: 'S(LT_IOGO) (capital Į)' },
  KC_CIRC: { name: 'Š', title: 'S(LT_SCAR) (capital Š)' },
  KC_AMPR: { name: 'Ų', title: 'S(LT_UOGO) (capital Ų)' },
  KC_ASTR: { name: 'Ū', title: 'S(LT_UMAC) (capital Ū)' },
  KC_PLUS: { name: 'Ž', title: 'S(LT_ZCAR) (capital Ž)' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: '`/~\nEsc',
    title: 'Esc normally, but ` when GUI is active or ~ when Shift is active'
  }
};
