/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
   * │ @ │ & │ é │ " │ ' │ ( │ § │ è │ ! │ ç │ à │ ) │ - │     │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
   * │     │ A │ Z │ E │ R │ T │ Y │ U │ I │ O │ P │ ^ │ $ │   │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
   * │      │ Q │ S │ D │ F │ G │ H │ J │ K │ L │ M │ ù │ ` │  │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
   * │    │ < │ W │ X │ C │ V │ B │ N │ , │ ; │ : │ = │        │
   * ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
   * │     │    │     │                       │     │    │     │
   * └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
   */
  // Row 1
  KC_GRV: { name: '#\n@', title: 'FR_AT' },
  KC_1: { name: '1\n&', title: 'FR_AMPR' },
  KC_2: { name: '2\né', title: 'FR_LEAC' },
  KC_3: { name: '3\n"', title: 'FR_DQUO' },
  KC_4: { name: "4\n'", title: 'FR_QUOT' },
  KC_5: { name: '5\n(', title: 'FR_LPRN' },
  KC_6: { name: '6\n§', title: 'FR_SECT' },
  KC_7: { name: '7\nè', title: 'FR_LEGR' },
  KC_8: { name: '8\n!', title: 'FR_EXLM' },
  KC_9: { name: '9\nç', title: 'FR_LCCE' },
  KC_0: { name: '0\nà', title: 'FR_LAGR' },
  KC_MINS: { name: '°\n)', title: 'FR_RPRN' },
  KC_EQL: { name: '_\n-', title: 'FR_MINS' },
  // Row 2
  KC_Q: { name: 'A', title: 'FR_A' },
  KC_W: { name: 'Z', title: 'FR_Z' },
  KC_E: { name: 'E', title: 'FR_E' },
  KC_R: { name: 'R', title: 'FR_R' },
  KC_T: { name: 'T', title: 'FR_T' },
  KC_Y: { name: 'Y', title: 'FR_Y' },
  KC_U: { name: 'U', title: 'FR_U' },
  KC_I: { name: 'I', title: 'FR_I' },
  KC_O: { name: 'O', title: 'FR_O' },
  KC_P: { name: 'P', title: 'FR_P' },
  KC_LBRC: { name: '¨\n^', title: 'FR_CIRC' },
  KC_RBRC: { name: '*\n$', title: 'FR_DLR' },
  // Row 3
  KC_A: { name: 'Q', title: 'FR_Q' },
  KC_S: { name: 'S', title: 'FR_S' },
  KC_D: { name: 'D', title: 'FR_D' },
  KC_F: { name: 'F', title: 'FR_F' },
  KC_G: { name: 'G', title: 'FR_G' },
  KC_H: { name: 'H', title: 'FR_H' },
  KC_J: { name: 'J', title: 'FR_J' },
  KC_K: { name: 'K', title: 'FR_K' },
  KC_L: { name: 'L', title: 'FR_L' },
  KC_SCLN: { name: 'M', title: 'FR_M' },
  KC_QUOT: { name: '%\nù', title: 'FR_LUGR' },
  KC_NUHS: { name: '£\n`', title: 'FR_GRV' },
  // Row 4
  KC_NUBS: { name: '>\n<', title: 'FR_LABK' },
  KC_Z: { name: 'W', title: 'FR_W' },
  KC_X: { name: 'X', title: 'FR_X' },
  KC_C: { name: 'C', title: 'FR_C' },
  KC_V: { name: 'V', title: 'FR_V' },
  KC_B: { name: 'B', title: 'FR_B' },
  KC_N: { name: 'N', title: 'FR_N' },
  KC_M: { name: '?\n,', title: 'FR_COMM' },
  KC_COMM: { name: '.\n;', title: 'FR_SCLN' },
  KC_DOT: { name: '/\n:', title: 'FR_COLN' },
  KC_SLSH: { name: '+\n=', title: 'FR_EQL' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
   * │ # │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ° │ _ │     │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
   * │     │   │   │   │   │   │   │   │   │   │   │ ¨ │ * │   │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
   * │      │   │   │   │   │   │   │   │   │   │   │ % │ £ │  │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
   * │    │ > │   │   │   │   │   │   │ ? │ . │ / │ + │        │
   * ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
   * │     │    │     │                       │     │    │     │
   * └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '#', title: 'FR_HASH' },
  KC_TILD: { name: '#', title: 'FR_HASH' },
  'S(KC_1)': { name: '1', title: 'FR_1' },
  KC_EXLM: { name: '1', title: 'FR_1' },
  'S(KC_2)': { name: '2', title: 'FR_2' },
  KC_AT: { name: '2', title: 'FR_2' },
  'S(KC_3)': { name: '3', title: 'FR_3' },
  KC_HASH: { name: '3', title: 'FR_3' },
  'S(KC_4)': { name: '4', title: 'FR_4' },
  KC_DLR: { name: '4', title: 'FR_4' },
  'S(KC_5)': { name: '5', title: 'FR_5' },
  KC_PERC: { name: '5', title: 'FR_5' },
  'S(KC_6)': { name: '6', title: 'FR_6' },
  KC_CIRC: { name: '6', title: 'FR_6' },
  'S(KC_7)': { name: '7', title: 'FR_7' },
  KC_AMPR: { name: '7', title: 'FR_7' },
  'S(KC_8)': { name: '8', title: 'FR_8' },
  KC_ASTR: { name: '8', title: 'FR_8' },
  'S(KC_9)': { name: '9', title: 'FR_9' },
  KC_LPRN: { name: '9', title: 'FR_9' },
  'S(KC_0)': { name: '0', title: 'FR_0' },
  KC_RPRN: { name: '0', title: 'FR_0' },
  'S(KC_MINS)': { name: '°', title: 'FR_DEG' },
  KC_UNDS: { name: '°', title: 'FR_DEG' },
  'S(KC_EQL)': { name: '_', title: 'FR_UNDS' },
  KC_PLUS: { name: '_', title: 'FR_UNDS' },
  // Row 2
  'S(KC_LBRC)': { name: '¨', title: 'FR_DIAE (dead)' },
  KC_LCBR: { name: '¨', title: 'FR_DIAE (dead)' },
  'S(KC_RBRC)': { name: '*', title: 'FR_ASTR' },
  KC_RCBR: { name: '*', title: 'FR_ASTR' },
  // Row 3
  'S(KC_QUOT)': { name: '%', title: 'FR_PERC' },
  KC_DQUO: { name: '%', title: 'FR_PERC' },
  'S(KC_NUHS)': { name: '£', title: 'FR_PND' },
  // Row 4
  'S(KC_NUBS)': { name: '>', title: 'FR_RABK' },
  'S(KC_M)': { name: '?', title: 'FR_QUES' },
  'S(KC_COMM)': { name: '.', title: 'FR_DOT' },
  KC_LT: { name: '.', title: 'FR_DOT' },
  'S(KC_DOT)': { name: '/', title: 'FR_SLSH' },
  KC_GT: { name: '/', title: 'FR_SLSH' },
  'S(KC_SLSH)': { name: '+', title: 'FR_PLUS' },
  KC_QUES: { name: '+', title: 'FR_PLUS' },

  /* Alted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
   * │ • │  │ ë │ “ │ ‘ │ { │ ¶ │ « │ ¡ │ Ç │ Ø │ } │ — │     │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
   * │     │ Æ │ Â │ Ê │ ® │ † │ Ú │ º │ î │ Œ │ π │ Ô │ € │   │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
   * │      │ ‡ │ Ò │ ∂ │ ƒ │ ﬁ │ Ì │ Ï │ È │ ¬ │ µ │ Ù │   │  │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
   * │    │ ≤ │ ‹ │ ≈ │ © │ ◊ │ ß │ ~ │ ∞ │ … │ ÷ │ ≠ │        │
   * ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
   * │     │    │     │                       │     │    │     │
   * └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
   */
  // Row 1
  'A(KC_GRV)': { name: '•', title: 'FR_BULT' },
  'A(KC_1)': { name: '', title: 'FR_APPL (Apple logo)' },
  'A(KC_2)': { name: 'ë', title: 'FR_LEDI' },
  'A(KC_3)': { name: '“', title: 'FR_LDQU' },
  'A(KC_4)': { name: '‘', title: 'FR_LSQU' },
  'A(KC_5)': { name: '{', title: 'FR_LCBR' },
  'A(KC_6)': { name: '¶', title: 'FR_PILC' },
  'A(KC_7)': { name: '«', title: 'FR_LDAQ' },
  'A(KC_8)': { name: '¡', title: 'FR_IEXL' },
  'A(KC_9)': { name: 'Ç', title: 'FR_CCCE' },
  'A(KC_0)': { name: 'Ø', title: 'FR_OSTR' },
  'A(KC_MINS)': { name: '}', title: 'FR_RCBR' },
  'A(KC_EQL)': { name: '—', title: 'FR_MDSH' },
  // Row 2
  'A(KC_Q)': { name: 'Æ', title: 'FR_AE' },
  'A(KC_W)': { name: 'Â', title: 'FR_CACI' },
  'A(KC_E)': { name: 'Ê', title: 'FR_ECIR' },
  'A(KC_R)': { name: '®', title: 'FR_REGD' },
  'A(KC_T)': { name: '†', title: 'FR_DAGG' },
  'A(KC_Y)': { name: 'Ú', title: 'FR_CUAC' },
  'A(KC_U)': { name: 'º', title: 'FR_MORD' },
  'A(KC_I)': { name: 'î', title: 'FR_LICI' },
  'A(KC_O)': { name: 'Œ', title: 'FR_OE' },
  'A(KC_P)': { name: 'π', title: 'FR_PI' },
  'A(KC_LBRC)': { name: 'Ô', title: 'FR_OCIR' },
  'A(KC_RBRC)': { name: '€', title: 'FR_EURO' },
  // Row 3
  'A(KC_A)': { name: '‡', title: 'FR_DDAG' },
  'A(KC_S)': { name: 'Ò', title: 'FR_COGR' },
  'A(KC_D)': { name: '∂', title: 'FR_PDIF' },
  'A(KC_F)': { name: 'ƒ', title: 'FR_FHK' },
  'A(KC_G)': { name: 'ﬁ', title: 'FR_FI' },
  'A(KC_H)': { name: 'Ì', title: 'FR_CIGR' },
  'A(KC_J)': { name: 'Ï', title: 'FR_CIDI' },
  'A(KC_K)': { name: 'È', title: 'FR_CEGR' },
  'A(KC_L)': { name: '¬', title: 'FR_NOT' },
  'A(KC_SCLN)': { name: 'µ', title: 'FR_MICR' },
  'A(KC_QUOT)': { name: 'Ù', title: 'FR_CUGR' },
  // Row 4
  'A(KC_NUBS)': { name: '≤', title: 'FR_LTEQ' },
  'A(KC_Z)': { name: '‹', title: 'FR_LSAQ' },
  'A(KC_X)': { name: '≈', title: 'FR_AEQL' },
  'A(KC_C)': { name: '©', title: 'FR_COPY' },
  'A(KC_V)': { name: '◊', title: 'FR_LOZN' },
  'A(KC_B)': { name: 'ß', title: 'FR_SS' },
  'A(KC_N)': { name: '~', title: 'FR_TILD (dead)' },
  'A(KC_M)': { name: '∞', title: 'FR_INFN' },
  'A(KC_COMM)': { name: '…', title: 'FR_ELLP' },
  'A(KC_DOT)': { name: '÷', title: 'FR_DIV' },
  'A(KC_SLSH)': { name: '≠', title: 'FR_NEQL' },

  /* Shift+Alted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬─────┐
   * │ Ÿ │ ´ │ „ │   │   │ [ │ å │ » │ Û │ Á │   │ ] │ – │     │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬───┤
   * │     │   │ Å │   │ ‚ │ ™ │   │ ª │ ï │   │ ∏ │   │ ¥ │   │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐  │
   * │      │ Ω │ ∑ │ ∆ │ · │ ﬂ │ Î │ Í │ Ë │ | │ Ó │ ‰ │   │  │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴──┤
   * │    │ ≥ │ › │ ⁄ │ ¢ │ √ │ ∫ │ ı │ ¿ │   │ \ │ ± │        │
   * ├────┴┬──┴─┬─┴───┼───┴───┴───┴───┴───┴───┼───┴─┬─┴──┬─────┤
   * │     │    │     │                       │     │    │     │
   * └─────┴────┴─────┴───────────────────────┴─────┴────┴─────┘
   */
  // Row 1
  'S(A(KC_GRV))': { name: 'Ÿ', title: 'FR_CYDI' },
  'S(A(KC_1))': { name: '´', title: 'FR_ACUT (dead)' },
  'S(A(KC_2))': { name: '„', title: 'FR_DLQU' },
  'S(A(KC_5))': { name: '[', title: 'FR_LBRC' },
  'S(A(KC_6))': { name: 'å', title: 'FR_LARI' },
  'S(A(KC_7))': { name: '»', title: 'FR_RDAQ' },
  'S(A(KC_8))': { name: 'Û', title: 'FR_CUCI' },
  'S(A(KC_9))': { name: 'Á', title: 'FR_CAAC' },
  'S(A(KC_MINS))': { name: ']', title: 'FR_RBRC' },
  'S(A(KC_EQL))': { name: '–', title: 'FR_NDSH' },
  // Row 2
  'S(A(KC_W))': { name: 'Å', title: 'FR_CARI' },
  'S(A(KC_R))': { name: '‚', title: 'FR_SLQU' },
  'S(A(KC_T))': { name: '™', title: 'FR_TM' },
  'S(A(KC_U))': { name: 'ª', title: 'FR_FORD' },
  'S(A(KC_I))': { name: 'ï', title: 'FR_LIDI' },
  'S(A(KC_P))': { name: '∏', title: 'FR_NARP' },
  'S(A(KC_RBRC))': { name: '¥', title: 'FR_YEN' },
  // Row 3
  'S(A(KC_A))': { name: 'Ω', title: 'FR_OMEG' },
  'S(A(KC_S))': { name: '∑', title: 'FR_NARS' },
  'S(A(KC_D))': { name: '∆', title: 'FR_INCR' },
  'S(A(KC_F))': { name: '·', title: 'FR_MDDT' },
  'S(A(KC_G))': { name: 'ﬂ', title: 'FR_FL' },
  'S(A(KC_H))': { name: 'Î', title: 'FR_CICI' },
  'S(A(KC_J))': { name: 'Í', title: 'FR_CIAC' },
  'S(A(KC_K))': { name: 'Ë', title: 'FR_CEDI' },
  'S(A(KC_L))': { name: '|', title: 'FR_PIPE' },
  'S(A(KC_SCLN))': { name: 'Ó', title: 'FR_COAC' },
  'S(A(KC_QUOT))': { name: '‰', title: 'FR_PERM' },
  // Row 4
  'S(A(KC_NUBS))': { name: '≥', title: 'FR_GTEQ' },
  'S(A(KC_Z))': { name: '›', title: 'FR_RSAQ' },
  'S(A(KC_X))': { name: '⁄', title: 'FR_FRSL' },
  'S(A(KC_C))': { name: '¢', title: 'FR_CENT' },
  'S(A(KC_V))': { name: '√', title: 'FR_SQRT' },
  'S(A(KC_B))': { name: '∫', title: 'FR_INTG' },
  'S(A(KC_N))': { name: 'ı', title: 'FR_DLSI' },
  'S(A(KC_M))': { name: '¿', title: 'FR_IQUE' },
  'S(A(KC_DOT))': { name: '\\', title: 'FR_BSLS' },
  'S(A(KC_SLSH))': { name: '±', title: 'FR_PLMN' },

  /* Other keys */
  KC_BSLS: { name: '£\n`', title: '' },
  'S(KC_BSLS)': { name: '£', title: '' },
  KC_COLN: { name: 'M', title: 'S(FR_M) (capital M)' },
  KC_PIPE: { name: '£', title: 'FR_PND' },

  SC_LSPO: { name: 'LS / 9', title: 'Left Shift when held, 9 when tapped' },
  SC_RSPC: { name: 'RS / 0', title: 'Right Shift when held, 0 when tapped' },
  SC_LCPO: { name: 'LC / 9', title: 'Left Control when held, 9 when tapped' },
  SC_RCPC: { name: 'RC / 0', title: 'Right Control when held, 0 when tapped' },
  SC_LAPO: { name: 'LA / 9', title: 'Left Alt when held, 9 when tapped' },
  SC_RAPC: { name: 'RA / 0', title: 'Right Alt when held, 0 when tapped' },

  QK_GESC: {
    name: '@/#\nEsc',
    title: 'Esc normally, but @ when GUI is active or # when Shift is active'
  }
};
