/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ | │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ' │ ¿ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ ´ │ + │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ Ñ │ { │ } │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ - │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '°  \n| ¬', title: 'LA_PIPE' },
  KC_1: { name: '!\n1', title: 'LA_1' },
  KC_2: { name: '"\n2', title: 'LA_2' },
  KC_3: { name: '·\n3', title: 'LA_3' },
  KC_4: { name: '$\n4', title: 'LA_4' },
  KC_5: { name: '%\n5', title: 'LA_5' },
  KC_6: { name: '&\n6', title: 'LA_6' },
  KC_7: { name: '/\n7', title: 'LA_7' },
  KC_8: { name: '(\n8', title: 'LA_8' },
  KC_9: { name: ')\n9', title: 'LA_9' },
  KC_0: { name: '=\n0', title: 'LA_0' },
  KC_MINS: { name: "?  \n' \\", title: 'LA_QUOT' },
  KC_EQL: { name: '¡\n¿', title: 'LA_IQUE' },
  // Row 2
  KC_Q: { name: 'Q  \n  @', title: 'LA_Q' },
  KC_W: { name: 'W', title: 'LA_W' },
  KC_E: { name: 'E  \n  €', title: 'LA_E' },
  KC_R: { name: 'R', title: 'LA_R' },
  KC_T: { name: 'T', title: 'LA_T' },
  KC_Y: { name: 'Y', title: 'LA_Y' },
  KC_U: { name: 'U', title: 'LA_U' },
  KC_I: { name: 'I', title: 'LA_I' },
  KC_O: { name: 'O', title: 'LA_O' },
  KC_P: { name: 'P', title: 'LA_P' },
  KC_LBRC: { name: '¨\n´', title: 'LA_ACUT' },
  KC_RBRC: { name: '*  \n+ ~', title: 'LA_PLUS' },
  // Row 3
  KC_A: { name: 'A', title: 'LA_A' },
  KC_S: { name: 'S', title: 'LA_S' },
  KC_D: { name: 'D', title: 'LA_D' },
  KC_F: { name: 'F', title: 'LA_F' },
  KC_G: { name: 'G', title: 'LA_G' },
  KC_H: { name: 'H', title: 'LA_H' },
  KC_J: { name: 'J', title: 'LA_J' },
  KC_K: { name: 'K', title: 'LA_K' },
  KC_L: { name: 'L', title: 'LA_L' },
  KC_SCLN: { name: 'Ñ', title: 'LA_NTIL' },
  KC_QUOT: { name: '[  \n{ ^', title: 'LA_LCBR' },
  KC_NUHS: { name: ']  \n} `', title: 'LA_RCBR' },
  // Row 4
  KC_NUBS: { name: '>\n<', title: 'LA_LABK' },
  KC_Z: { name: 'Z', title: 'LA_Z' },
  KC_X: { name: 'X', title: 'LA_X' },
  KC_C: { name: 'C', title: 'LA_C' },
  KC_V: { name: 'V', title: 'LA_V' },
  KC_B: { name: 'B', title: 'LA_B' },
  KC_N: { name: 'N', title: 'LA_N' },
  KC_M: { name: 'M', title: 'LA_M' },
  KC_COMM: { name: ';\n,', title: 'LA_COMM' },
  KC_DOT: { name: ':\n.', title: 'LA_DOT' },
  KC_SLSH: { name: '_\n-', title: 'LA_MINS' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ° │ ! │ " │ # │ $ │ % │ & │ / │ ( │ ) │ = │ ? │ ¡ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ ¨ │ * │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ [ │ ] │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '°', title: 'LA_MORD' },
  KC_TILD: { name: '°', title: 'LA_MORD' },
  'S(KC_1)': { name: '!', title: 'LA_EXLM' },
  KC_EXLM: { name: '!', title: 'LA_EXLM' },
  'S(KC_2)': { name: '"', title: 'LA_DQUO' },
  KC_AT: { name: '"', title: 'LA_DQUO' },
  'S(KC_3)': { name: '#', title: 'LA_NUMB' },
  KC_HASH: { name: '#', title: 'LA_NUMB' },
  'S(KC_4)': { name: '$', title: 'LA_DLR' },
  KC_DLR: { name: '$', title: 'LA_DLR' },
  'S(KC_5)': { name: '%', title: 'LA_PERC' },
  KC_PERC: { name: '%', title: 'LA_PERC' },
  'S(KC_6)': { name: '&', title: 'LA_AMPR' },
  KC_CIRC: { name: '&', title: 'LA_AMPR' },
  'S(KC_7)': { name: '/', title: 'LA_SLSH' },
  KC_AMPR: { name: '/', title: 'LA_SLSH' },
  'S(KC_8)': { name: '(', title: 'LA_LPRN' },
  KC_ASTR: { name: '(', title: 'LA_LPRN' },
  'S(KC_9)': { name: ')', title: 'LA_RPRN' },
  KC_LPRN: { name: ')', title: 'LA_RPRN' },
  'S(KC_0)': { name: '=', title: 'LA_EQL' },
  KC_RPRN: { name: '=', title: 'LA_EQL' },
  'S(KC_MINS)': { name: '?', title: 'LA_QUES' },
  KC_UNDS: { name: '?', title: 'LA_QUES' },
  'S(KC_EQL)': { name: '¡', title: 'LA_IEXL' },
  KC_PLUS: { name: '¡', title: 'LA_IEXL' },
  // Row 2
  'S(KC_LBRC)': { name: '¨', title: 'LA_DIAE' },
  KC_LCBR: { name: '¨', title: 'LA_DIAE' },
  'S(KC_RBRC)': { name: '*', title: 'LA_ASTR' },
  KC_RCBR: { name: '*', title: 'LA_ASTR' },
  // Row 3
  'S(KC_QUOT)': { name: '[', title: 'LA_LBRC' },
  KC_DQUO: { name: '[', title: 'LA_LBRC' },
  // Row 4
  'S(KC_NUBS)': { name: '>', title: 'LA_RABK' },
  'S(KC_COMM)': { name: ';', title: 'LA_SCLN' },
  KC_LT: { name: ';', title: 'LA_SCLN' },
  'S(KC_DOT)': { name: ':', title: 'LA_COLN' },
  KC_GT: { name: ':', title: 'LA_COLN' },
  'S(KC_SLSH)': { name: '_', title: 'LA_UNDS' },
  KC_QUES: { name: '_', title: 'LA_UNDS' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ¬ │   │   │   │   │   │   │   │   │   │   │ \ │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ @ │   │ € │   │   │   │   │   │   │   │   │ ~ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ ^ │ ` │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_GRV)': { name: '¬', title: 'LA_NOT' },
  'ALGR(KC_EQL)': { name: '\\', title: 'LA_BSLS' },
  // Row 2
  'ALGR(KC_Q)': { name: '@', title: 'LA_AT' },
  'ALGR(KC_E)': { name: '€', title: 'LA_EUR' },
  'ALGR(KC_RBRC)': { name: '~', title: 'LA_TILD' },
  // Row 3
  'ALGR(KC_QUOT)': { name: '^', title: 'LA_CIRC' },
  'ALGR(KC_NUHS)': { name: '`', title: 'LA_ACUT' },

  /* Other keys */
  KC_BSLS: { name: 'Ç', title: '' },
  'S(KC_BSLS)': { name: 'Ç', title: '' },
  KC_COLN: { name: 'Ñ', title: 'S(ES_NTIL) (capital Ñ)' },
  KC_PIPE: { name: 'Ç', title: 'ES_CCED (capital Ç)' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / =', title: 'Right Shift when held, = when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / =', title: 'Right Control when held, = when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / =', title: 'Right Alt when held, = when tapped' },

  QK_GESC: {
    name: 'º/ª\nEsc',
    title: 'Esc normally, but º when GUI is active or ª when Shift is active'
  }
};
