/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ \ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ' │ « │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ + │ ´ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ Ç │ º │ ~ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ - │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '|\n\\', title: 'PT_BSLS' },
  KC_1: { name: '!\n1', title: 'PT_1' },
  KC_2: { name: '"\n2', title: 'PT_2' },
  KC_3: { name: '#\n3', title: 'PT_3' },
  KC_4: { name: '$\n4', title: 'PT_4' },
  KC_5: { name: '%\n5', title: 'PT_5' },
  KC_6: { name: '&\n6', title: 'PT_6' },
  KC_7: { name: '/\n7', title: 'PT_7' },
  KC_8: { name: '(\n8', title: 'PT_8' },
  KC_9: { name: ')\n9', title: 'PT_9' },
  KC_0: { name: '=\n0', title: 'PT_0' },
  KC_MINS: { name: "?\n'", title: 'PT_QUOT' },
  KC_EQL: { name: '»\n«', title: 'PT_LDAQ' },
  // Row 2
  KC_Q: { name: 'Q', title: 'PT_Q' },
  KC_W: { name: 'W', title: 'PT_W' },
  KC_E: { name: 'E', title: 'PT_E' },
  KC_R: { name: 'R', title: 'PT_R' },
  KC_T: { name: 'T', title: 'PT_T' },
  KC_Y: { name: 'Y', title: 'PT_Y' },
  KC_U: { name: 'U', title: 'PT_U' },
  KC_I: { name: 'I', title: 'PT_I' },
  KC_O: { name: 'O', title: 'PT_O' },
  KC_P: { name: 'P', title: 'PT_P' },
  KC_LBRC: { name: '*\n+', title: 'PT_PLUS' },
  KC_RBRC: { name: '`\n´', title: 'PT_ACUT (dead)' },
  // Row 3
  KC_A: { name: 'A', title: 'PT_A' },
  KC_S: { name: 'S', title: 'PT_S' },
  KC_D: { name: 'D', title: 'PT_D' },
  KC_F: { name: 'F', title: 'PT_F' },
  KC_G: { name: 'G', title: 'PT_G' },
  KC_H: { name: 'H', title: 'PT_H' },
  KC_J: { name: 'J', title: 'PT_J' },
  KC_K: { name: 'K', title: 'PT_K' },
  KC_L: { name: 'L', title: 'PT_L' },
  KC_SCLN: { name: 'Ç', title: 'PT_CCED' },
  KC_QUOT: { name: 'ª\nº', title: 'PT_MORD' },
  KC_NUHS: { name: '^\n~', title: 'PT_TILD (dead)' },
  // Row 4
  KC_NUBS: { name: '>\n<', title: 'PT_LABK' },
  KC_Z: { name: 'Z', title: 'PT_Z' },
  KC_X: { name: 'X', title: 'PT_X' },
  KC_C: { name: 'C', title: 'PT_C' },
  KC_V: { name: 'V', title: 'PT_V' },
  KC_B: { name: 'B', title: 'PT_B' },
  KC_N: { name: 'N', title: 'PT_N' },
  KC_M: { name: 'M', title: 'PT_M' },
  KC_COMM: { name: ';\n,', title: 'PT_COMM' },
  KC_DOT: { name: ':\n.', title: 'PT_DOT' },
  KC_SLSH: { name: '_\n-', title: 'PT_MINS' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ | │ ! │ " │ # │ $ │ % │ & │ / │ ( │ ) │ = │ ? │ » │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ * │ ` │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ ª │ ^ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '|', title: 'PT_PIPE' },
  KC_TILD: { name: '|', title: 'PT_PIPE' },
  'S(KC_1)': { name: '!', title: 'PT_EXLM' },
  KC_EXLM: { name: '!', title: 'PT_EXLM' },
  'S(KC_2)': { name: '"', title: 'PT_DQUO' },
  KC_AT: { name: '"', title: 'PT_DQUO' },
  'S(KC_3)': { name: '#', title: 'PT_HASH' },
  KC_HASH: { name: '#', title: 'PT_HASH' },
  'S(KC_4)': { name: '$', title: 'PT_DLR' },
  KC_DLR: { name: '$', title: 'PT_DLR' },
  'S(KC_5)': { name: '%', title: 'PT_PERC' },
  KC_PERC: { name: '%', title: 'PT_PERC' },
  'S(KC_6)': { name: '&', title: 'PT_AMPR' },
  KC_CIRC: { name: '&', title: 'PT_AMPR' },
  'S(KC_7)': { name: '/', title: 'PT_SLSH' },
  KC_AMPR: { name: '/', title: 'PT_SLSH' },
  'S(KC_8)': { name: '(', title: 'PT_LPRN' },
  KC_ASTR: { name: '(', title: 'PT_LPRN' },
  'S(KC_9)': { name: ')', title: 'PT_RPRN' },
  KC_LPRN: { name: ')', title: 'PT_RPRN' },
  'S(KC_0)': { name: '=', title: 'PT_EQL' },
  KC_RPRN: { name: '=', title: 'PT_EQL' },
  'S(KC_MINS)': { name: '?', title: 'PT_QUES' },
  KC_UNDS: { name: '?', title: 'PT_QUES' },
  'S(KC_EQL)': { name: '»', title: 'PT_RDAQ' },
  KC_PLUS: { name: '»', title: 'PT_RDAQ' },
  // Row 2
  'S(KC_LBRC)': { name: '*', title: 'PT_ASTR' },
  KC_LCBR: { name: '*', title: 'PT_ASTR' },
  'S(KC_RBRC)': { name: '`', title: 'PT_GRV (dead)' },
  KC_RCBR: { name: '`', title: 'PT_GRV (dead)' },
  // Row 3
  'S(KC_QUOT)': { name: 'ª', title: 'PT_FORD' },
  KC_DQUO: { name: 'ª', title: 'PT_FORD' },
  'S(KC_NUHS)': { name: '^', title: 'PT_CIRC (dead)' },
  // Row 4
  'S(KC_NUBS)': { name: '>', title: 'PT_RABK' },
  'S(KC_COMM)': { name: ';', title: 'PT_SCLN' },
  KC_LT: { name: ';', title: 'PT_SCLN' },
  'S(KC_DOT)': { name: ':', title: 'PT_COLN' },
  KC_GT: { name: ':', title: 'PT_COLN' },
  'S(KC_SLSH)': { name: '_', title: 'PT_UNDS' },
  KC_QUES: { name: '_', title: 'PT_UNDS' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │   │ @ │ £ │ § │   │   │ { │ [ │ ] │ } │   │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ € │   │   │   │   │   │   │   │ ¨ │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_2)': { name: '@', title: 'PT_AT' },
  'ALGR(KC_3)': { name: '£', title: 'PT_PND' },
  'ALGR(KC_4)': { name: '§', title: 'PT_SECT' },
  'ALGR(KC_7)': { name: '{', title: 'PT_LCBR' },
  'ALGR(KC_8)': { name: '[', title: 'PT_LBRC' },
  'ALGR(KC_9)': { name: ']', title: 'PT_RBRC' },
  'ALGR(KC_0)': { name: '}', title: 'PT_RCBR' },
  // Row 2
  'ALGR(KC_LBRC)': { name: '¨', title: 'PT_DIAE (dead)' },
  'ALGR(KC_E)': { name: '€', title: 'PT_EURO' },

  /* Other keys */
  KC_BSLS: { name: '^\n~', title: '(dead)' },
  'S(KC_BSLS)': { name: '^', title: '(dead)' },
  KC_COLN: { name: 'Ç', title: 'S(PT_CCED) (capital Ç)' },
  KC_PIPE: { name: '^', title: 'PT_CIRC' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / =', title: 'Right Shift when held, = when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / =', title: 'Right Control when held, = when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / =', title: 'Right Alt when held, = when tapped' },

  QK_GESC: {
    name: '\\/|\nEsc',
    title: 'Esc normally, but \\ when GUI is active or | when Shift is active'
  }
};
