/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ Ё │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Й │ Ц │ У │ К │ Е │ Н │ Г │ Ш │ Щ │ З │ Х │ Ъ │  \  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │ Ф │ Ы │ В │ А │ П │ Р │ О │ Л │ Д │ Ж │ Э │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │ Я │ Ч │ С │ М │ И │ Т │ Ь │ Б │ Ю │ . │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: 'Ё', title: 'RU_YO' },
  KC_1: { name: '!\n1', title: 'RU_1' },
  KC_2: { name: '"\n2', title: 'RU_2' },
  KC_3: { name: '№\n3', title: 'RU_3' },
  KC_4: { name: ';\n4', title: 'RU_4' },
  KC_5: { name: '%\n5', title: 'RU_5' },
  KC_6: { name: ':\n6', title: 'RU_6' },
  KC_7: { name: '?\n7', title: 'RU_7' },
  KC_8: { name: '*\n8', title: 'RU_8' },
  KC_9: { name: '(\n9', title: 'RU_9' },
  KC_0: { name: ')\n0', title: 'RU_0' },
  KC_MINS: { name: '_\n-', title: 'RU_MINS' },
  KC_EQL: { name: '+\n=', title: 'RU_EQL' },
  // Row 2
  KC_Q: { name: 'Й', title: 'RU_SHTI' },
  KC_W: { name: 'Ц', title: 'RU_TSE' },
  KC_E: { name: 'У', title: 'RU_U' },
  KC_R: { name: 'К', title: 'RU_KA' },
  KC_T: { name: 'Е', title: 'RU_IE' },
  KC_Y: { name: 'Н', title: 'RU_EN' },
  KC_U: { name: 'Г', title: 'RU_GHE' },
  KC_I: { name: 'Ш', title: 'RU_SHA' },
  KC_O: { name: 'Щ', title: 'RU_SHCH' },
  KC_P: { name: 'З', title: 'RU_ZE' },
  KC_LBRC: { name: 'Х', title: 'RU_HA' },
  KC_RBRC: { name: 'Ъ', title: 'RU_HARD' },
  KC_BSLS: { name: '/\n\\', title: 'RU_BSLS' },
  // Row 3
  KC_A: { name: 'Ф', title: 'RU_EF' },
  KC_S: { name: 'Ы', title: 'RU_YERU' },
  KC_D: { name: 'В', title: 'RU_VE' },
  KC_F: { name: 'А', title: 'RU_A' },
  KC_G: { name: 'П', title: 'RU_PE' },
  KC_H: { name: 'Р', title: 'RU_ER' },
  KC_J: { name: 'О', title: 'RU_O' },
  KC_K: { name: 'Л', title: 'RU_EL' },
  KC_L: { name: 'Д', title: 'RU_DE' },
  KC_SCLN: { name: 'Ж', title: 'RU_ZHE' },
  KC_QUOT: { name: 'Э', title: 'RU_E' },
  // Row 4
  KC_Z: { name: 'Я', title: 'RU_YA' },
  KC_X: { name: 'Ч', title: 'RU_CHE' },
  KC_C: { name: 'С', title: 'RU_ES' },
  KC_V: { name: 'М', title: 'RU_EM' },
  KC_B: { name: 'И', title: 'RU_I' },
  KC_N: { name: 'Т', title: 'RU_TE' },
  KC_M: { name: 'Ь', title: 'RU_SOFT' },
  KC_COMM: { name: 'Б', title: 'RU_BE' },
  KC_DOT: { name: 'Ю', title: 'RU_YU' },
  KC_SLSH: { name: ',\n.', title: 'RU_DOT' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │ ! │ " │ № │ ; │ % │ : │ ? │ * │ ( │ ) │ _ │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │   │  /  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │   │   │   │   │   │   │   │   │   │   │   │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │   │   │   │   │   │   │   │   │   │ , │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_1)': { name: '!', title: 'RU_EXLM' },
  KC_EXLM: { name: '!', title: 'RU_EXLM' },
  'S(KC_2)': { name: '"', title: 'RU_DQUO' },
  KC_AT: { name: '"', title: 'RU_DQUO' },
  'S(KC_3)': { name: '№', title: 'RU_NUM' },
  KC_HASH: { name: '№', title: 'RU_NUM' },
  'S(KC_4)': { name: ';', title: 'RU_SCLN' },
  KC_DLR: { name: ';', title: 'RU_SCLN' },
  'S(KC_5)': { name: '%', title: 'RU_PERC' },
  KC_PERC: { name: '%', title: 'RU_PERC' },
  'S(KC_6)': { name: ':', title: 'RU_COLN' },
  KC_CIRC: { name: ':', title: 'RU_COLN' },
  'S(KC_7)': { name: '?', title: 'RU_QUES' },
  KC_AMPR: { name: '?', title: 'RU_QUES' },
  'S(KC_8)': { name: '*', title: 'RU_ASTR' },
  KC_ASTR: { name: '*', title: 'RU_ASTR' },
  'S(KC_9)': { name: '(', title: 'RU_LPRN' },
  KC_LPRN: { name: '(', title: 'RU_LPRN' },
  'S(KC_0)': { name: ')', title: 'RU_RPRN' },
  KC_RPRN: { name: ')', title: 'RU_RPRN' },
  'S(KC_MINS)': { name: '_', title: 'RU_UNDS' },
  KC_UNDS: { name: '_', title: 'RU_UNDS' },
  'S(KC_EQL)': { name: '+', title: 'RU_PLUS' },
  KC_PLUS: { name: '+', title: 'RU_PLUS' },
  // Row 2
  'S(KC_BSLS)': { name: '/', title: 'RU_SLSH' },
  KC_PIPE: { name: '/', title: 'RU_SLSH' },
  // Row 4
  'S(KC_SLSH)': { name: ',', title: 'RU_COMM' },
  KC_QUES: { name: ',', title: 'RU_COMM' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │   │   │   │   │   │   │   │ ₽ │   │   │   │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │   │   │   │   │   │   │   │   │   │   │   │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_8)': { name: '₽', title: 'RU_RUBL' },

  /* Other keys */
  KC_NUHS: { name: '/\n\\', title: '' },
  'S(KC_NUHS)': { name: '/', title: '' },
  KC_NUBS: { name: '/\n\\', title: '' },
  'S(KC_NUBS)': { name: '/', title: '' },
  KC_TILD: { name: 'Ё', title: 'S(RU_YO) (capital Ё)' },
  KC_LCBR: { name: 'Х', title: 'S(RU_HA) (capital Х)' },
  KC_RCBR: { name: 'Ъ', title: 'S(RU_HARD) (capital Ъ)' },
  KC_LT: { name: 'Б', title: 'S(RU_BE) (capital Б)' },
  KC_GT: { name: 'Ю', title: 'S(RU_YU) (capital Ю)' },
  KC_COLN: { name: 'Ж', title: 'S(RU_ZHE) (capital Ж)' },
  KC_DQUO: { name: 'Э', title: 'S(RU_E) (capital Э)' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: 'Ё\nEsc',
    title: 'Esc normally, but Ё when Shift or GUI is active'
  },

  KC_PDOT: { name: ',', title: '' } // No RU alias exist in QMK
};
