/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * JP106-layout (Japanese Standard)
 *
 * For more information, see
 * http://www2d.biglobe.ne.jp/~msyk/keyboard/layout/usbkeycode.html
 * note: This website is written in Japanese.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┐
   * │Z↔H│ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ ^ │ ¥ │   │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ @ │ [ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │ Eisū │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ; │ : │ ] │    │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────┤
   * │        │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ / │ \ │      │
   * ├─────┬──┴┬──┴──┬┴───┴┬──┴───┴──┬┴───┴┬──┴┬──┴┬──┴┬──┴┬─────┤
   * │     │   │     │Muhen│         │ Hen │K↔H│   │   │   │     │
   * └─────┴───┴─────┴─────┴─────────┴─────┴───┴───┴───┴───┴─────┘
   */
  // Row 1
  KC_GRV: {
    name: '半角 / 全角',
    title: 'JP_ZKHK (半角 Zenkaku ↔ 全角 Hankaku ↔ 漢字 Kanji)'
  },
  KC_1: { name: '!\n1', title: 'JP_1' },
  KC_2: { name: '"\n2', title: 'JP_2' },
  KC_3: { name: '#\n3', title: 'JP_3' },
  KC_4: { name: '$\n4', title: 'JP_4' },
  KC_5: { name: '%\n5', title: 'JP_5' },
  KC_6: { name: '&\n6', title: 'JP_6' },
  KC_7: { name: "'\n7", title: 'JP_7' },
  KC_8: { name: '(\n8', title: 'JP_8' },
  KC_9: { name: ')\n9', title: 'JP_9' },
  KC_0: { name: '0', title: 'JP_0' },
  KC_MINS: { name: '=\n-', title: 'JP_MINS' },
  KC_EQL: { name: '~\n^', title: 'JP_CIRC' },
  KC_INT3: { name: '|\n¥', title: 'JP_YEN' },
  // Row 2
  KC_Q: { name: 'Q', title: 'JP_Q' },
  KC_W: { name: 'W', title: 'JP_W' },
  KC_E: { name: 'E', title: 'JP_E' },
  KC_R: { name: 'R', title: 'JP_R' },
  KC_T: { name: 'T', title: 'JP_T' },
  KC_Y: { name: 'Y', title: 'JP_Y' },
  KC_U: { name: 'U', title: 'JP_U' },
  KC_I: { name: 'I', title: 'JP_I' },
  KC_O: { name: 'O', title: 'JP_O' },
  KC_P: { name: 'P', title: 'JP_P' },
  KC_LBRC: { name: '`\n@', title: 'JP_AT' },
  KC_RBRC: { name: '{\n[', title: 'JP_LBRC' },
  // Row 3
  KC_CAPS: { name: 'Caps Lock\nEisū', title: 'JP_EISU (英数)' },
  KC_A: { name: 'A', title: 'JP_A' },
  KC_S: { name: 'S', title: 'JP_S' },
  KC_D: { name: 'D', title: 'JP_D' },
  KC_F: { name: 'F', title: 'JP_F' },
  KC_G: { name: 'G', title: 'JP_G' },
  KC_H: { name: 'H', title: 'JP_H' },
  KC_J: { name: 'J', title: 'JP_J' },
  KC_K: { name: 'K', title: 'JP_K' },
  KC_L: { name: 'L', title: 'JP_L' },
  KC_SCLN: { name: '+\n;', title: 'JP_SCLN' },
  KC_QUOT: { name: '*\n:', title: 'JP_COLN' },
  KC_NUHS: { name: '}\n]', title: 'JP_RBRC' },
  // Row 4
  KC_Z: { name: 'Z', title: 'JP_Z' },
  KC_X: { name: 'X', title: 'JP_X' },
  KC_C: { name: 'C', title: 'JP_C' },
  KC_V: { name: 'V', title: 'JP_V' },
  KC_B: { name: 'B', title: 'JP_B' },
  KC_N: { name: 'N', title: 'JP_N' },
  KC_M: { name: 'M', title: 'JP_M' },
  KC_COMM: { name: '<\n,', title: 'JP_COMM' },
  KC_DOT: { name: '>\n.', title: 'JP_DOT' },
  KC_SLSH: { name: '?\n/', title: 'JP_SLSH' },
  KC_INT1: { name: '_\n\\', title: 'JP_BSLS' },
  // Row 5
  KC_INT5: { name: '無変換', title: 'JP_MHEN (無変換 Muhenkan)' },
  KC_INT4: { name: '変換', title: 'JP_HENK (変換 Henkan)' },
  KC_INT2: {
    name: 'カタカナ\nひらがな',
    title: 'JP_KANA (カタカナ Katakana ↔ ひらがな Hiragana ↔ ローマ字 Rōmaji)'
  },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┐
   * │   │ ! │ " │ # │ $ │ % │ & │ ' │ ( │ ) │   │ = │ ~ │ | │   │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┤
   * │     │   │   │   │   │   │   │   │   │   │   │ ` │ { │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │ Caps │   │   │   │   │   │   │   │   │   │ + │ * │ } │    │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────┤
   * │        │   │   │   │   │   │   │   │ < │ > │ ? │ _ │      │
   * ├─────┬──┴┬──┴──┬┴───┴┬──┴───┴──┬┴───┴┬──┴┬──┴┬──┴┬──┴┬─────┤
   * │     │   │     │     │         │     │   │   │   │   │     │
   * └─────┴───┴─────┴─────┴─────────┴─────┴───┴───┴───┴───┴─────┘
   */
  // Row 1
  'S(KC_1)': { name: '!', title: 'JP_EXLM' },
  KC_EXLM: { name: '!', title: 'JP_EXLM' },
  'S(KC_2)': { name: '"', title: 'JP_DQUO' },
  KC_AT: { name: '"', title: 'JP_DQUO' },
  'S(KC_3)': { name: '#', title: 'JP_HASH' },
  KC_HASH: { name: '#', title: 'JP_HASH' },
  'S(KC_4)': { name: '$', title: 'JP_DLR' },
  KC_DLR: { name: '$', title: 'JP_DLR' },
  'S(KC_5)': { name: '%', title: 'JP_PERC' },
  KC_PERC: { name: '%', title: 'JP_PERC' },
  'S(KC_6)': { name: '&', title: 'JP_AMPR' },
  KC_CIRC: { name: '&', title: 'JP_AMPR' },
  'S(KC_7)': { name: "'", title: 'JP_QUOT' },
  KC_AMPR: { name: "'", title: 'JP_QUOT' },
  'S(KC_8)': { name: '(', title: 'JP_LPRN' },
  KC_ASTR: { name: '(', title: 'JP_LPRN' },
  'S(KC_9)': { name: ')', title: 'JP_RPRN' },
  KC_LPRN: { name: ')', title: 'JP_RPRN' },
  'S(KC_MINS)': { name: '=', title: 'JP_EQL' },
  KC_UNDS: { name: '=', title: 'JP_EQL' },
  'S(KC_EQL)': { name: '~', title: 'JP_TILD' },
  KC_PLUS: { name: '~', title: 'JP_TILD' },
  'S(KC_INT3)': { name: '|', title: 'JP_PIPE' },
  // Row 2
  'S(KC_LBRC)': { name: '`', title: 'JP_GRV' },
  KC_LCBR: { name: '`', title: 'JP_GRV' },
  'S(KC_RBRC)': { name: '{', title: 'JP_LCBR' },
  KC_RCBR: { name: '{', title: 'JP_LCBR' },
  // Row 3
  'S(KC_CAPS)': { name: 'Caps Lock', title: 'JP_CAPS' },
  'S(KC_SCLN)': { name: '+', title: 'JP_PLUS' },
  KC_COLN: { name: '+', title: 'JP_PLUS' },
  'S(KC_QUOT)': { name: '*', title: 'JP_ASTR' },
  KC_DQUO: { name: '*', title: 'JP_ASTR' },
  'S(KC_NUHS)': { name: '}', title: 'JP_RCBR' },
  // Row 4
  'S(KC_COMM)': { name: '<', title: 'JP_LABK' },
  KC_LT: { name: '<', title: 'JP_LABK' },
  'S(KC_DOT)': { name: '>', title: 'JP_RABK' },
  KC_GT: { name: '>', title: 'JP_RABK' },
  'S(KC_SLSH)': { name: '?', title: 'JP_QUES' },
  KC_QUES: { name: '?', title: 'JP_QUES' },
  'S(KC_INT1)': { name: '_', title: 'JP_UNDS' },

  /* Other keys */
  KC_BSLS: { name: '}\n]', title: '' },
  'S(KC_BSLS)': { name: '}', title: '' },
  KC_NUBS: { name: '}\n]', title: '' },
  'S(KC_NUBS)': { name: '}', title: '' },
  KC_TILD: { name: '半角 / 全角', title: 'S(JP_ZKHK)' },
  KC_RPRN: { name: '0', title: 'S(JP_0)' },
  KC_PIPE: { name: '}', title: 'JP_RCBR' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / 0', title: 'Right Shift when held, 0 when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / 0', title: 'Right Control when held, 0 when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / 0', title: 'Right Alt when held, 0 when tapped' },

  QK_GESC: {
    name: '半角/全角\nEsc',
    title:
      'Esc normally, but Zenkaku ↔ Hankaku ↔ Kanji when Shift or GUI is active'
  }
};
