/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ [ │ ] │  ₩  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ; │ ' │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ / │          │
   * ├─────┬──┴┬──┴──┬┴──┬┴───┴───┴───┴──┬┴──┬┴───┴┬──┴┬───┬─────┤
   * │     │   │     │Hnj│               │H↔Y│     │   │   │     │
   * └─────┴───┴─────┴───┴───────────────┴───┴─────┴───┴───┴─────┘
   */
  // Row 1
  KC_GRV: { name: '~\n`', title: 'KR_GRV' },
  KC_1: { name: '!\n1', title: 'KR_1' },
  KC_2: { name: '@\n2', title: 'KR_2' },
  KC_3: { name: '#\n3', title: 'KR_3' },
  KC_4: { name: '$\n4', title: 'KR_4' },
  KC_5: { name: '%\n5', title: 'KR_5' },
  KC_6: { name: '^\n6', title: 'KR_6' },
  KC_7: { name: '&\n7', title: 'KR_7' },
  KC_8: { name: '*\n8', title: 'KR_8' },
  KC_9: { name: '(\n9', title: 'KR_9' },
  KC_0: { name: ')\n0', title: 'KR_0' },
  KC_MINS: { name: '_\n-', title: 'KR_MINS' },
  KC_EQL: { name: '+\n=', title: 'KR_EQL' },
  // Row 2
  KC_Q: { name: 'Q', title: 'KR_Q' },
  KC_W: { name: 'W', title: 'KR_W' },
  KC_E: { name: 'E', title: 'KR_E' },
  KC_R: { name: 'R', title: 'KR_R' },
  KC_T: { name: 'T', title: 'KR_T' },
  KC_Y: { name: 'Y', title: 'KR_Y' },
  KC_U: { name: 'U', title: 'KR_U' },
  KC_I: { name: 'I', title: 'KR_I' },
  KC_O: { name: 'O', title: 'KR_O' },
  KC_P: { name: 'P', title: 'KR_P' },
  KC_LBRC: { name: '{\n[', title: 'KR_LBRC' },
  KC_RBRC: { name: '}\n]', title: 'KR_RBRC' },
  KC_BSLS: { name: '|\n₩', title: 'KR_WON' },
  // Row 3
  KC_A: { name: 'A', title: 'KR_A' },
  KC_S: { name: 'S', title: 'KR_S' },
  KC_D: { name: 'D', title: 'KR_D' },
  KC_F: { name: 'F', title: 'KR_F' },
  KC_G: { name: 'G', title: 'KR_G' },
  KC_H: { name: 'H', title: 'KR_H' },
  KC_J: { name: 'J', title: 'KR_J' },
  KC_K: { name: 'K', title: 'KR_K' },
  KC_L: { name: 'L', title: 'KR_L' },
  KC_SCLN: { name: ':\n;', title: 'KR_SCLN' },
  KC_QUOT: { name: '"\n\'', title: 'KR_QUOT' },
  // Row 4
  KC_Z: { name: 'Z', title: 'KR_Z' },
  KC_X: { name: 'X', title: 'KR_X' },
  KC_C: { name: 'C', title: 'KR_C' },
  KC_V: { name: 'V', title: 'KR_V' },
  KC_B: { name: 'B', title: 'KR_B' },
  KC_N: { name: 'N', title: 'KR_N' },
  KC_M: { name: 'M', title: 'KR_M' },
  KC_COMM: { name: '<\n,', title: 'KR_COMM' },
  KC_DOT: { name: '>\n.', title: 'KR_DOT' },
  KC_SLSH: { name: '?\n/', title: 'KR_SLSH' },
  // Row 5
  KC_LNG2: { name: '한자', title: 'KR_HANJ (한자 Hanja)' },
  KC_LNG1: { name: '한 / 영', title: 'KR_HAEN (한 Han ↔ 영 Yeong)' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │ ! │ @ │ # │ $ │ % │ ^ │ & │ * │ ( │ ) │ _ │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ { │ } │  |  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │   │   │   │   │   │   │   │   │   │ : │ " │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │   │   │   │   │   │   │   │ < │ > │ ? │          │
   * ├─────┬──┴┬──┴──┬┴──┬┴───┴───┴───┴──┬┴──┬┴───┴┬──┴┬───┬─────┤
   * │     │   │     │   │               │   │     │   │   │     │
   * └─────┴───┴─────┴───┴───────────────┴───┴─────┴───┴───┴─────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', title: 'KR_TILD' },
  KC_TILD: { name: '~', title: 'KR_TILD' },
  'S(KC_1)': { name: '!', title: 'KR_EXLM' },
  KC_EXLM: { name: '!', title: 'KR_EXLM' },
  'S(KC_2)': { name: '@', title: 'KR_AT' },
  KC_AT: { name: '@', title: 'KR_AT' },
  'S(KC_3)': { name: '#', title: 'KR_HASH' },
  KC_HASH: { name: '#', title: 'KR_HASH' },
  'S(KC_4)': { name: '$', title: 'KR_DLR' },
  KC_DLR: { name: '$', title: 'KR_DLR' },
  'S(KC_5)': { name: '%', title: 'KR_PERC' },
  KC_PERC: { name: '%', title: 'KR_PERC' },
  'S(KC_6)': { name: '^', title: 'KR_CIRC' },
  KC_CIRC: { name: '^', title: 'KR_CIRC' },
  'S(KC_7)': { name: '&', title: 'KR_AMPR' },
  KC_AMPR: { name: '&', title: 'KR_AMPR' },
  'S(KC_8)': { name: '*', title: 'KR_ASTR' },
  KC_ASTR: { name: '*', title: 'KR_ASTR' },
  'S(KC_9)': { name: '(', title: 'KR_LPRN' },
  KC_LPRN: { name: '(', title: 'KR_LPRN' },
  'S(KC_0)': { name: ')', title: 'KR_RPRN' },
  KC_RPRN: { name: ')', title: 'KR_RPRN' },
  'S(KC_MINS)': { name: '_', title: 'KR_UNDS' },
  KC_UNDS: { name: '_', title: 'KR_UNDS' },
  'S(KC_EQL)': { name: '+', title: 'KR_PLUS' },
  KC_PLUS: { name: '+', title: 'KR_PLUS' },
  // Row 2
  'S(KC_LBRC)': { name: '{', title: 'KR_LCBR' },
  KC_LCBR: { name: '{', title: 'KR_LCBR' },
  'S(KC_RBRC)': { name: '}', title: 'KR_RCBR' },
  KC_RCBR: { name: '}', title: 'KR_RCBR' },
  'S(KC_BSLS)': { name: '|', title: 'KR_PIPE' },
  KC_PIPE: { name: '|', title: 'KR_PIPE' },
  // Row 3
  'S(KC_SCLN)': { name: ':', title: 'KR_COLN' },
  KC_COLN: { name: ':', title: 'KR_COLN' },
  'S(KC_QUOT)': { name: '"', title: 'KR_DQUO' },
  KC_DQUO: { name: '"', title: 'KR_DQUO' },
  // Row 4
  'S(KC_COMM)': { name: '<', title: 'KR_LABK' },
  KC_LT: { name: '<', title: 'KR_LABK' },
  'S(KC_DOT)': { name: '>', title: 'KR_RABK' },
  KC_GT: { name: '>', title: 'KR_RABK' },
  'S(KC_SLSH)': { name: '?', title: 'KR_QUES' },
  KC_QUES: { name: '?', title: 'KR_QUES' },

  /* Other keys */
  KC_NUHS: { name: '|\n₩', title: '' },
  'S(KC_NUHS)': { name: '|', title: '' },
  KC_NUBS: { name: '|\n₩', title: '' },
  'S(KC_NUBS)': { name: '|', title: '' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: '`/~\nEsc',
    title: 'Esc normally, but ` when GUI is active or ~ when Shift is active'
  }
};
