/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ' │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Љ │ Њ │ Е │ Р │ Т │ З │ У │ И │ О │ П │ Ш │ Ђ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ А │ С │ Д │ Ф │ Г │ Х │ Ј │ К │ Л │ Ч │ Ћ │ Ж │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Ѕ │ Џ │ Ц │ В │ Б │ Н │ М │ , │ . │ - │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '~\n`', title: 'RS_GRV' },
  KC_1: { name: '!\n1', title: 'RS_1' },
  KC_2: { name: '"\n2', title: 'RS_2' },
  KC_3: { name: '#\n3', title: 'RS_3' },
  KC_4: { name: '$\n4', title: 'RS_4' },
  KC_5: { name: '%\n5', title: 'RS_5' },
  KC_6: { name: '&\n6', title: 'RS_6' },
  KC_7: { name: '/\n7', title: 'RS_7' },
  KC_8: { name: '(\n8', title: 'RS_8' },
  KC_9: { name: ')\n9', title: 'RS_9' },
  KC_0: { name: '=\n0', title: 'RS_0' },
  KC_MINS: { name: "?\n'", title: 'RS_QUOT (dead)' },
  KC_EQL: { name: '*\n+', title: 'RS_PLUS' },
  // Row 2
  KC_Q: { name: 'Љ', title: 'RS_LJE' },
  KC_W: { name: 'Њ', title: 'RS_NJE' },
  KC_E: { name: 'Е', title: 'RS_IE' },
  KC_R: { name: 'Р', title: 'RS_ER' },
  KC_T: { name: 'Т', title: 'RS_TE' },
  KC_Y: { name: 'З', title: 'RS_ZE' },
  KC_U: { name: 'У', title: 'RS_U' },
  KC_I: { name: 'И', title: 'RS_I' },
  KC_O: { name: 'О', title: 'RS_O' },
  KC_P: { name: 'П', title: 'RS_PE' },
  KC_LBRC: { name: 'Ш', title: 'RS_SHA' },
  KC_RBRC: { name: 'Ђ', title: 'RS_DJE' },
  // Row 3
  KC_A: { name: 'А', title: 'RS_A' },
  KC_S: { name: 'С', title: 'RS_ES' },
  KC_D: { name: 'Д', title: 'RS_DE' },
  KC_F: { name: 'Ф', title: 'RS_EF' },
  KC_G: { name: 'Г', title: 'RS_GHE' },
  KC_H: { name: 'Х', title: 'RS_HA' },
  KC_J: { name: 'Ј', title: 'RS_JE' },
  KC_K: { name: 'К', title: 'RS_KA' },
  KC_L: { name: 'Л', title: 'RS_EL' },
  KC_SCLN: { name: 'Ч', title: 'RS_CHE' },
  KC_QUOT: { name: 'Ћ', title: 'RS_TSHE' },
  KC_NUHS: { name: 'Ж', title: 'RS_ZHE' },
  // Row 4
  KC_NUBS: { name: '>\n<', title: 'RS_LABK' },
  KC_Z: { name: 'Ѕ', title: 'RS_DZE' },
  KC_X: { name: 'Џ', title: 'RS_DZHE' },
  KC_C: { name: 'Ц', title: 'RS_TSE' },
  KC_V: { name: 'В', title: 'RS_VE' },
  KC_B: { name: 'Б', title: 'RS_BE' },
  KC_N: { name: 'Н', title: 'RS_EN' },
  KC_M: { name: 'М', title: 'RS_EM' },
  KC_COMM: { name: ';\n,', title: 'RS_COMM' },
  KC_DOT: { name: ':\n.', title: 'RS_DOT' },
  KC_SLSH: { name: '_\n-', title: 'RS_MINS' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │ ! │ " │ # │ $ │ % │ & │ / │ ( │ ) │ = │ ? │ * │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', title: 'RS_TILD' },
  KC_TILD: { name: '~', title: 'RS_TILD' },
  'S(KC_1)': { name: '!', title: 'RS_EXLM' },
  KC_EXLM: { name: '!', title: 'RS_EXLM' },
  'S(KC_2)': { name: '"', title: 'RS_DQUO' },
  KC_AT: { name: '"', title: 'RS_DQUO' },
  'S(KC_3)': { name: '#', title: 'RS_HASH' },
  KC_HASH: { name: '#', title: 'RS_HASH' },
  'S(KC_4)': { name: '$', title: 'RS_DLR' },
  KC_DLR: { name: '$', title: 'RS_DLR' },
  'S(KC_5)': { name: '%', title: 'RS_PERC' },
  KC_PERC: { name: '%', title: 'RS_PERC' },
  'S(KC_6)': { name: '&', title: 'RS_AMPR' },
  KC_CIRC: { name: '&', title: 'RS_AMPR' },
  'S(KC_7)': { name: '/', title: 'RS_SLSH' },
  KC_AMPR: { name: '/', title: 'RS_SLSH' },
  'S(KC_8)': { name: '(', title: 'RS_LPRN' },
  KC_ASTR: { name: '(', title: 'RS_LPRN' },
  'S(KC_9)': { name: ')', title: 'RS_RPRN' },
  KC_LPRN: { name: ')', title: 'RS_RPRN' },
  'S(KC_0)': { name: '=', title: 'RS_EQL' },
  KC_RPRN: { name: '=', title: 'RS_EQL' },
  'S(KC_MINS)': { name: '?', title: 'RS_QUES' },
  KC_UNDS: { name: '?', title: 'RS_QUES' },
  'S(KC_EQL)': { name: '*', title: 'RS_ASTR' },
  KC_PLUS: { name: '*', title: 'RS_ASTR' },
  // Row 4
  'S(KC_NUBS)': { name: '>', title: 'RS_RABK' },
  'S(KC_COMM)': { name: ';', title: 'RS_SCLN' },
  KC_LT: { name: ';', title: 'RS_SCLN' },
  'S(KC_DOT)': { name: ':', title: 'RS_COLN' },
  KC_GT: { name: ':', title: 'RS_COLN' },
  'S(KC_SLSH)': { name: '_', title: 'RS_UNDS' },
  KC_QUES: { name: '_', title: 'RS_UNDS' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │   │   │   │   │   │   │   │   │   │   │   │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ € │   │   │   │   │   │   │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 2
  'ALGR(KC_E)': { name: '€', title: 'RS_EURO' },

  /* Other keys */
  KC_BSLS: { name: 'Ж', title: '' },
  'S(KC_BSLS)': { name: 'Ж', title: '' },
  KC_LCBR: { name: 'Ш', title: 'S(RS_SHA) (capital Ш)' },
  KC_RCBR: { name: 'Ђ', title: 'S(RS_DJE) (capital Ђ)' },
  KC_COLN: { name: 'Ч', title: 'S(RS_CHE) (capital Ч)' },
  KC_PIPE: { name: 'Ж', title: 'RS_ZHE (capital Ж)' },
  KC_DQUO: { name: 'Ћ', title: 'S(RS_TSHE) (capital Ћ)' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / =', title: 'Right Shift when held, = when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / =', title: 'Right Control when held, = when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / =', title: 'Right Alt when held, = when tapped' },

  QK_GESC: {
    name: '`/~\nEsc',
    title: 'Esc normally, but ` when GUI is active or ~ when Shift is active'
  }
};
