/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ² │ & │ é │ " │ ' │ ( │ § │ è │ ! │ ç │ à │ ) │ - │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ A │ Z │ E │ R │ T │ Y │ U │ I │ O │ P │ ^ │ $ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ Q │ S │ D │ F │ G │ H │ J │ K │ L │ M │ ù │ µ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ W │ X │ C │ V │ B │ N │ , │ ; │ : │ = │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '³\n²', title: 'BE_SUP2' },
  KC_1: { name: '1\n&', title: 'BE_AMPR' },
  KC_2: { name: '2\né', title: 'BE_EACU' },
  KC_3: { name: '3\n"', title: 'BE_DQUO' },
  KC_4: { name: "4\n'", title: 'BE_QUOT' },
  KC_5: { name: '5\n(', title: 'BE_LPRN' },
  KC_6: { name: '6\n§', title: 'BE_SECT' },
  KC_7: { name: '7\nè', title: 'BE_EGRV' },
  KC_8: { name: '8\n!', title: 'BE_EXLM' },
  KC_9: { name: '9\nç', title: 'BE_CCED' },
  KC_0: { name: '0\nà', title: 'BE_AGRV' },
  KC_MINS: { name: '°\n)', title: 'BE_RPRN' },
  KC_EQL: { name: '_\n-', title: 'BE_MINS' },
  // Row 2
  KC_Q: { name: 'A', title: 'BE_A' },
  KC_W: { name: 'Z', title: 'BE_Z' },
  KC_E: { name: 'E', title: 'BE_E' },
  KC_R: { name: 'R', title: 'BE_R' },
  KC_T: { name: 'T', title: 'BE_T' },
  KC_Y: { name: 'Y', title: 'BE_Y' },
  KC_U: { name: 'U', title: 'BE_U' },
  KC_I: { name: 'I', title: 'BE_I' },
  KC_O: { name: 'O', title: 'BE_O' },
  KC_P: { name: 'P', title: 'BE_P' },
  KC_LBRC: { name: '¨\n^', title: 'BE_DCIR (dead)' },
  KC_RBRC: { name: '*\n$', title: 'BE_DLR' },
  // Row 3
  KC_A: { name: 'Q', title: 'BE_Q' },
  KC_S: { name: 'S', title: 'BE_S' },
  KC_D: { name: 'D', title: 'BE_D' },
  KC_F: { name: 'F', title: 'BE_F' },
  KC_G: { name: 'G', title: 'BE_G' },
  KC_H: { name: 'H', title: 'BE_H' },
  KC_J: { name: 'J', title: 'BE_J' },
  KC_K: { name: 'K', title: 'BE_K' },
  KC_L: { name: 'L', title: 'BE_L' },
  KC_SCLN: { name: 'M', title: 'BE_M' },
  KC_QUOT: { name: '%\nù', title: 'BE_UGRV' },
  KC_NUHS: { name: '£\nµ', title: 'BE_MICR' },
  // Row 4
  KC_NUBS: { name: '>\n<', title: 'BE_LABK' },
  KC_Z: { name: 'W', title: 'BE_W' },
  KC_X: { name: 'X', title: 'BE_X' },
  KC_C: { name: 'C', title: 'BE_C' },
  KC_V: { name: 'V', title: 'BE_V' },
  KC_B: { name: 'B', title: 'BE_B' },
  KC_N: { name: 'N', title: 'BE_N' },
  KC_M: { name: '?\n,', title: 'BE_COMM' },
  KC_COMM: { name: '.\n;', title: 'BE_SCLN' },
  KC_DOT: { name: '/\n:', title: 'BE_COLN' },
  KC_SLSH: { name: '+\n=', title: 'BE_EQL' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ³ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ° │ _ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ ¨ │ * │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ % │ £ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │ ? │ . │ / │ + │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '³', title: 'BE_SUP3' },
  KC_TILD: { name: '³', title: 'BE_SUP3' },
  'S(KC_1)': { name: '1', title: 'BE_1' },
  KC_EXLM: { name: '1', title: 'BE_1' },
  'S(KC_2)': { name: '2', title: 'BE_2' },
  KC_AT: { name: '2', title: 'BE_2' },
  'S(KC_3)': { name: '3', title: 'BE_3' },
  KC_HASH: { name: '3', title: 'BE_3' },
  'S(KC_4)': { name: '4', title: 'BE_4' },
  KC_DLR: { name: '4', title: 'BE_4' },
  'S(KC_5)': { name: '5', title: 'BE_5' },
  KC_PERC: { name: '5', title: 'BE_5' },
  'S(KC_6)': { name: '6', title: 'BE_6' },
  KC_CIRC: { name: '6', title: 'BE_6' },
  'S(KC_7)': { name: '7', title: 'BE_7' },
  KC_AMPR: { name: '7', title: 'BE_7' },
  'S(KC_8)': { name: '8', title: 'BE_8' },
  KC_ASTR: { name: '8', title: 'BE_8' },
  'S(KC_9)': { name: '9', title: 'BE_9' },
  KC_LPRN: { name: '9', title: 'BE_9' },
  'S(KC_0)': { name: '0', title: 'BE_0' },
  KC_RPRN: { name: '0', title: 'BE_0' },
  'S(KC_MINS)': { name: '°', title: 'BE_DEG' },
  KC_UNDS: { name: '°', title: 'BE_DEG' },
  'S(KC_EQL)': { name: '_', title: 'BE_UNDS' },
  KC_PLUS: { name: '_', title: 'BE_UNDS' },
  // Row 2
  'S(KC_LBRC)': { name: '¨', title: 'BE_DIAE (dead)' },
  KC_LCBR: { name: '¨', title: 'BE_DIAE (dead)' },
  'S(KC_RBRC)': { name: '*', title: 'BE_ASTR' },
  KC_RCBR: { name: '*', title: 'BE_ASTR' },
  // Row 3
  'S(KC_QUOT)': { name: '%', title: 'BE_PERC' },
  KC_DQUO: { name: '%', title: 'BE_PERC' },
  'S(KC_NUHS)': { name: '£', title: 'BE_PND' },
  // Row 4
  'S(KC_NUBS)': { name: '>', title: 'BE_RABK' },
  'S(KC_M)': { name: '?', title: 'BE_QUES' },
  'S(KC_COMM)': { name: '.', title: 'BE_DOT' },
  KC_LT: { name: '.', title: 'BE_DOT' },
  'S(KC_DOT)': { name: '/', title: 'BE_SLSH' },
  KC_GT: { name: '/', title: 'BE_SLSH' },
  'S(KC_SLSH)': { name: '+', title: 'BE_PLUS' },
  KC_QUES: { name: '+', title: 'BE_PLUS' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │ | │ @ │ # │   │   │ ^ │   │   │ { │ } │   │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ € │   │   │   │   │   │   │   │ [ │ ] │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ ´ │ ` │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ \ │   │   │   │   │   │   │   │   │   │ ~ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_1)': { name: '|', title: 'BE_PIPE' },
  'ALGR(KC_2)': { name: '@', title: 'BE_AT' },
  'ALGR(KC_3)': { name: '#', title: 'BE_HASH' },
  'ALGR(KC_6)': { name: '^', title: 'BE_CIRC' },
  'ALGR(KC_9)': { name: '{', title: 'BE_LCBR' },
  'ALGR(KC_0)': { name: '}', title: 'BE_RCBR' },
  // Row 2
  'ALGR(KC_E)': { name: '€', title: 'BE_EURO' },
  'ALGR(KC_LBRC)': { name: '[', title: 'BE_LBRC' },
  'ALGR(KC_RBRC)': { name: ']', title: 'BE_RBRC' },
  // Row 3
  'ALGR(KC_QUOT)': { name: '´', title: 'BE_ACUT (dead)' },
  'ALGR(KC_NUHS)': { name: '`', title: 'BE_GRV (dead)' },
  // Row 4
  'ALGR(KC_NUBS)': { name: '\\', title: 'BE_BSLS' },
  'ALGR(KC_SLSH)': { name: '~', title: 'BE_TILD' },

  /* Other keys */
  KC_BSLS: { name: '£\nµ', title: '' },
  'S(KC_BSLS)': { name: '£', title: '' },
  KC_COLN: { name: 'M', title: 'S(BE_M) (capital M)' },
  KC_PIPE: { name: '£', title: 'BE_PND' },

  SC_LSPO: { name: 'LS / 9', title: 'Left Shift when held, 9 when tapped' },
  SC_RSPC: { name: 'RS / 0', title: 'Right Shift when held, 0 when tapped' },
  SC_LCPO: { name: 'LC / 9', title: 'Left Control when held, 9 when tapped' },
  SC_RCPC: { name: 'RC / 0', title: 'Right Control when held, 0 when tapped' },
  SC_LAPO: { name: 'LA / 9', title: 'Left Alt when held, 9 when tapped' },
  SC_RAPC: { name: 'RA / 0', title: 'Right Alt when held, 0 when tapped' },

  QK_GESC: {
    name: '²/³\nEsc',
    title: 'Esc normally, but ² when GUI is active or ³ when Shift is active'
  }
};
