/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ § │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ' │ ^ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Z │ U │ I │ O │ P │ ü │ ¨ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ö │ ä │ $ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Y │ X │ C │ V │ B │ N │ M │ , │ . │ - │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '°\n§', title: 'CH_SECT' },
  KC_1: { name: '+\n1', title: 'CH_1' },
  KC_2: { name: '"\n2', title: 'CH_2' },
  KC_3: { name: '*\n3', title: 'CH_3' },
  KC_4: { name: 'ç\n4', title: 'CH_4' },
  KC_5: { name: '%\n5', title: 'CH_5' },
  KC_6: { name: '&\n6', title: 'CH_6' },
  KC_7: { name: '/\n7', title: 'CH_7' },
  KC_8: { name: '(\n8', title: 'CH_8' },
  KC_9: { name: ')\n9', title: 'CH_9' },
  KC_0: { name: '=\n0', title: 'CH_0' },
  KC_MINS: { name: "?\n'", title: 'CH_QUOT' },
  KC_EQL: { name: '`\n^', title: 'CH_CIRC (dead)' },
  // Row 2
  KC_Q: { name: 'Q', title: 'CH_Q' },
  KC_W: { name: 'W', title: 'CH_W' },
  KC_E: { name: 'E', title: 'CH_E' },
  KC_R: { name: 'R', title: 'CH_R' },
  KC_T: { name: 'T', title: 'CH_T' },
  KC_Y: { name: 'Z', title: 'CH_Z' },
  KC_U: { name: 'U', title: 'CH_U' },
  KC_I: { name: 'I', title: 'CH_I' },
  KC_O: { name: 'O', title: 'CH_O' },
  KC_P: { name: 'P', title: 'CH_P' },
  KC_LBRC: { name: 'è\nü', title: 'CH_UDIA' },
  KC_RBRC: { name: '!\n¨', title: 'CH_DIAE (dead)' },
  // Row 3
  KC_A: { name: 'A', title: 'CH_A' },
  KC_S: { name: 'S', title: 'CH_S' },
  KC_D: { name: 'D', title: 'CH_D' },
  KC_F: { name: 'F', title: 'CH_F' },
  KC_G: { name: 'G', title: 'CH_G' },
  KC_H: { name: 'H', title: 'CH_H' },
  KC_J: { name: 'J', title: 'CH_J' },
  KC_K: { name: 'K', title: 'CH_K' },
  KC_L: { name: 'L', title: 'CH_L' },
  KC_SCLN: { name: 'é\nö', title: 'CH_ODIA' },
  KC_QUOT: { name: 'à\nä', title: 'CH_ADIA' },
  KC_NUHS: { name: '£\n$', title: 'CH_DLR' },
  // Row 4
  KC_NUBS: { name: '>\n<', title: 'CH_LABK' },
  KC_Z: { name: 'Y', title: 'CH_Y' },
  KC_X: { name: 'X', title: 'CH_X' },
  KC_C: { name: 'C', title: 'CH_C' },
  KC_V: { name: 'V', title: 'CH_V' },
  KC_B: { name: 'B', title: 'CH_B' },
  KC_N: { name: 'N', title: 'CH_N' },
  KC_M: { name: 'M', title: 'CH_M' },
  KC_COMM: { name: ';\n,', title: 'CH_COMM' },
  KC_DOT: { name: ':\n.', title: 'CH_DOT' },
  KC_SLSH: { name: '_\n-', title: 'CH_MINS' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ° │ + │ " │ * │ ç │ % │ & │ / │ ( │ ) │ = │ ? │ ` │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ è │ ! │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │ é │ à │ £ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '°', title: 'CH_DEG' },
  KC_TILD: { name: '°', title: 'CH_DEG' },
  'S(KC_1)': { name: '+', title: 'CH_PLUS' },
  KC_EXLM: { name: '+', title: 'CH_PLUS' },
  'S(KC_2)': { name: '"', title: 'CH_DQUO' },
  KC_AT: { name: '"', title: 'CH_DQUO' },
  'S(KC_3)': { name: '*', title: 'CH_ASTR' },
  KC_HASH: { name: '*', title: 'CH_ASTR' },
  'S(KC_4)': { name: 'ç', title: 'CH_CCED' },
  KC_DLR: { name: 'ç', title: 'CH_CCED' },
  'S(KC_5)': { name: '%', title: 'CH_PERC' },
  KC_PERC: { name: '%', title: 'CH_PERC' },
  'S(KC_6)': { name: '&', title: 'CH_AMPR' },
  KC_CIRC: { name: '&', title: 'CH_AMPR' },
  'S(KC_7)': { name: '/', title: 'CH_SLSH' },
  KC_AMPR: { name: '/', title: 'CH_SLSH' },
  'S(KC_8)': { name: '(', title: 'CH_LPRN' },
  KC_ASTR: { name: '(', title: 'CH_LPRN' },
  'S(KC_9)': { name: ')', title: 'CH_RPRN' },
  KC_LPRN: { name: ')', title: 'CH_RPRN' },
  'S(KC_0)': { name: '=', title: 'CH_EQL' },
  KC_RPRN: { name: '=', title: 'CH_EQL' },
  'S(KC_MINS)': { name: '?', title: 'CH_QUES' },
  KC_UNDS: { name: '?', title: 'CH_QUES' },
  'S(KC_EQL)': { name: '`', title: 'CH_GRV (dead)' },
  KC_PLUS: { name: '`', title: 'CH_GRV (dead)' },
  // Row 2
  'S(KC_LBRC)': { name: 'è', title: 'CH_EGRV' },
  KC_LCBR: { name: 'è', title: 'CH_EGRV' },
  'S(KC_RBRC)': { name: '!', title: 'CH_EXLM' },
  KC_RCBR: { name: '!', title: 'CH_EXLM' },
  // Row 3
  'S(KC_SCLN)': { name: 'é', title: 'CH_EACU' },
  KC_COLN: { name: 'é', title: 'CH_EACU' },
  'S(KC_QUOT)': { name: 'à', title: 'CH_AGRV' },
  KC_DQUO: { name: 'à', title: 'CH_AGRV' },
  'S(KC_NUHS)': { name: '£', title: 'CH_PND' },
  // Row 4
  'S(KC_NUBS)': { name: '>', title: 'CH_RABK' },
  'S(KC_COMM)': { name: ';', title: 'CH_SCLN' },
  KC_LT: { name: ';', title: 'CH_SCLN' },
  'S(KC_DOT)': { name: ':', title: 'CH_COLN' },
  KC_GT: { name: ':', title: 'CH_COLN' },
  'S(KC_SLSH)': { name: '_', title: 'CH_UNDS' },
  KC_QUES: { name: '_', title: 'CH_UNDS' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │ ¦ │ @ │ # │   │   │ ¬ │ | │ ¢ │   │   │ ´ │ ~ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ € │   │   │   │   │   │   │   │ [ │ ] │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ { │ } │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ \ │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_1)': { name: '¦', title: 'CH_BRKP' },
  'ALGR(KC_2)': { name: '@', title: 'CH_AT' },
  'ALGR(KC_3)': { name: '#', title: 'CH_HASH' },
  'ALGR(KC_6)': { name: '¬', title: 'CH_NOT' },
  'ALGR(KC_7)': { name: '|', title: 'CH_PIPE' },
  'ALGR(KC_8)': { name: '¢', title: 'CH_CENT' },
  'ALGR(KC_MINS)': { name: '´', title: 'CH_ACUT (dead)' },
  'ALGR(KC_EQL)': { name: '~', title: 'CH_TILD (dead)' },
  // Row 2
  'ALGR(KC_E)': { name: '€', title: 'CH_EURO' },
  'ALGR(KC_LBRC)': { name: '[', title: 'CH_LBRC' },
  'ALGR(KC_RBRC)': { name: ']', title: 'CH_RBRC' },
  // Row 3
  'ALGR(KC_QUOT)': { name: '{', title: 'CH_LCBR' },
  'ALGR(KC_NUHS)': { name: '}', title: 'CH_RCBR' },
  // Row 4
  'ALGR(KC_NUBS)': { name: '\\', title: 'CH_BSLS' },

  /* Other keys */
  KC_BSLS: { name: '£\n$', title: '' },
  'S(KC_BSLS)': { name: '£', title: '' },
  KC_PIPE: { name: '£', title: 'CH_PND' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / =', title: 'Right Shift when held, = when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / =', title: 'Right Control when held, = when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / =', title: 'Right Alt when held, = when tapped' },

  QK_GESC: {
    name: '§/°\nEsc',
    title: 'Esc normally, but § when GUI is active or ° when Shift is active'
  }
};
