/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ^ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ ` │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ X │ V │ L │ C │ W │ K │ H │ G │ F │ Q │ ß │ ´ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │  L3  │ U │ I │ A │ E │ O │ S │ N │ R │ T │ D │ Y │ L3│    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │L4 │ Ü │ Ö │ Ä │ P │ Z │ B │ M │ , │ . │ J │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │ L4 │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '^', title: 'NE_CIRC (dead)' },
  KC_1: { name: '1', title: 'NE_1' },
  KC_2: { name: '2', title: 'NE_2' },
  KC_3: { name: '3', title: 'NE_3' },
  KC_4: { name: '4', title: 'NE_4' },
  KC_5: { name: '5', title: 'NE_5' },
  KC_6: { name: '6', title: 'NE_6' },
  KC_7: { name: '7', title: 'NE_7' },
  KC_8: { name: '8', title: 'NE_8' },
  KC_9: { name: '9', title: 'NE_9' },
  KC_0: { name: '0', title: 'NE_0' },
  KC_MINS: { name: '-', title: 'NE_MINS' },
  KC_EQL: { name: '`', title: 'NE_GRV (dead)' },
  // Row 2
  KC_Q: { name: 'X', title: 'NE_X' },
  KC_W: { name: 'V', title: 'NE_V' },
  KC_E: { name: 'L', title: 'NE_L' },
  KC_R: { name: 'C', title: 'NE_C' },
  KC_T: { name: 'W', title: 'NE_W' },
  KC_Y: { name: 'K', title: 'NE_K' },
  KC_U: { name: 'H', title: 'NE_H' },
  KC_I: { name: 'G', title: 'NE_G' },
  KC_O: { name: 'F', title: 'NE_F' },
  KC_P: { name: 'Q', title: 'NE_Q' },
  KC_LBRC: { name: 'ß', title: 'NE_SS' },
  KC_RBRC: { name: '´', title: 'NE_ACUT (dead)' },
  // Row 3
  KC_CAPS: { name: '(layer 3)', title: 'NE_L3L' },
  KC_A: { name: 'U', title: 'NE_U' },
  KC_S: { name: 'I', title: 'NE_I' },
  KC_D: { name: 'A', title: 'NE_A' },
  KC_F: { name: 'E', title: 'NE_E' },
  KC_G: { name: 'O', title: 'NE_O' },
  KC_H: { name: 'S', title: 'NE_S' },
  KC_J: { name: 'N', title: 'NE_N' },
  KC_K: { name: 'R', title: 'NE_R' },
  KC_L: { name: 'T', title: 'NE_T' },
  KC_SCLN: { name: 'D', title: 'NE_D' },
  KC_QUOT: { name: 'Y', title: 'NE_Y' },
  KC_NUHS: { name: '(layer 3)', title: 'NE_L3R' },
  // Row 4
  KC_NUBS: { name: '(layer 4)', title: 'NE_L4L' },
  KC_Z: { name: 'Ü', title: 'NE_UDIA' },
  KC_X: { name: 'Ö', title: 'NE_ODIA' },
  KC_C: { name: 'Ä', title: 'NE_ADIA' },
  KC_V: { name: 'P', title: 'NE_P' },
  KC_B: { name: 'Z', title: 'NE_Z' },
  KC_N: { name: 'B', title: 'NE_B' },
  KC_M: { name: 'M', title: 'NE_M' },
  KC_COMM: { name: ',', title: 'NE_COMM' },
  KC_DOT: { name: '.', title: 'NE_DOT' },
  KC_SLSH: { name: 'J', title: 'NE_J' },
  // Row 5
  KC_ALGR: { name: '(layer 4)', title: 'NE_L4R' },

  /* Other keys */
  KC_BSLS: { name: '(layer 3)', title: '' },
  'S(KC_BSLS)': { name: '(layer 3)', title: '' },
  KC_TILD: { name: '^', title: 'S(NE_CIRC)' },
  KC_EXLM: { name: '1', title: 'S(NE_1)' },
  KC_AT: { name: '2', title: 'S(NE_2)' },
  KC_HASH: { name: '3', title: 'S(NE_3)' },
  KC_DLR: { name: '4', title: 'S(NE_4)' },
  KC_PERC: { name: '5', title: 'S(NE_5)' },
  KC_CIRC: { name: '6', title: 'S(NE_6)' },
  KC_AMPR: { name: '7', title: 'S(NE_7)' },
  KC_ASTR: { name: '8', title: 'S(NE_8)' },
  KC_LPRN: { name: '9', title: 'S(NE_9)' },
  KC_RPRN: { name: '0', title: 'S(NE_0)' },
  KC_UNDS: { name: '-', title: 'S(NE_MINS)' },
  KC_PLUS: { name: '`', title: 'S(NE_GRV)' },
  KC_LCBR: { name: 'ß', title: 'S(NE_SS) (capital ß)' },
  KC_RCBR: { name: '´', title: 'S(NE_ACUT)' },
  KC_LT: { name: ',', title: 'S(NE_COMM)' },
  KC_GT: { name: '.', title: 'S(NE_DOT)' },
  KC_COLN: { name: 'D', title: 'S(NE_D) (capital D)' },
  KC_PIPE: { name: '(layer 3)', title: 'NE_L3R' },
  KC_QUES: { name: 'J', title: 'S(NE_J) (capital J)' },
  KC_DQUO: { name: 'Y', title: 'S(NE_Y) (capital Y)' },

  SC_LSPO: { name: 'LS / 9', title: 'Left Shift when held, 9 when tapped' },
  SC_RSPC: { name: 'RS / 0', title: 'Right Shift when held, 0 when tapped' },
  SC_LCPO: { name: 'LC / 9', title: 'Left Control when held, 9 when tapped' },
  SC_RCPC: { name: 'RC / 0', title: 'Right Control when held, 0 when tapped' },
  SC_LAPO: { name: 'LA / 9', title: 'Left Alt when held, 9 when tapped' },
  SC_RAPC: { name: 'RA / 0', title: 'Right Alt when held, 0 when tapped' },

  QK_GESC: {
    name: '^\nEsc',
    title: 'Esc normally, but ^ when Shift or GUI is active'
  }
};
