/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ ! │ - │ / │ ; │ : │ , │ . │ = │ ( │ ) │ ? │ X │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Ą │ Ž │ E │ R │ T │ Y │ U │ I │ O │ P │ Į │ W │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ Š │ G │ H │ J │ K │ L │ Ų │ Ė │ Q │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Z │ Ū │ C │ V │ B │ N │ M │ Č │ F │ Ę │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '~\n`', title: 'LT_GRV' },
  KC_1: { name: '1\n!', title: 'LT_EXLM' },
  KC_2: { name: '2\n-', title: 'LT_MINS' },
  KC_3: { name: '3\n/', title: 'LT_SLSH' },
  KC_4: { name: '4\n;', title: 'LT_SCLN' },
  KC_5: { name: '5\n:', title: 'LT_COLN' },
  KC_6: { name: '6\n,', title: 'LT_COMM' },
  KC_7: { name: '7\n.', title: 'LT_DOT' },
  KC_8: { name: '8\n=', title: 'LT_EQL' },
  KC_9: { name: '9\n(', title: 'LT_LPRN' },
  KC_0: { name: '0\n)', title: 'LT_RPRN' },
  KC_MINS: { name: '+\n?', title: 'LT_QUES' },
  KC_EQL: { name: 'X', title: 'LT_X' },
  // Row 2
  KC_Q: { name: 'Ą', title: 'LT_AOGO' },
  KC_W: { name: 'Ž', title: 'LT_ZCAR' },
  KC_E: { name: 'E', title: 'LT_E' },
  KC_R: { name: 'R', title: 'LT_R' },
  KC_T: { name: 'T', title: 'LT_T' },
  KC_Y: { name: 'Y', title: 'LT_Y' },
  KC_U: { name: 'U', title: 'LT_U' },
  KC_I: { name: 'I', title: 'LT_I' },
  KC_O: { name: 'O', title: 'LT_O' },
  KC_P: { name: 'P', title: 'LT_P' },
  KC_LBRC: { name: 'Į', title: 'LT_IOGO' },
  KC_RBRC: { name: 'W', title: 'LT_W' },
  // Row 3
  KC_A: { name: 'A', title: 'LT_A' },
  KC_S: { name: 'S', title: 'LT_S' },
  KC_D: { name: 'D', title: 'LT_D' },
  KC_F: { name: 'Š', title: 'LT_SCAR' },
  KC_G: { name: 'G', title: 'LT_G' },
  KC_H: { name: 'H', title: 'LT_H' },
  KC_J: { name: 'J', title: 'LT_J' },
  KC_K: { name: 'K', title: 'LT_K' },
  KC_L: { name: 'L', title: 'LT_L' },
  KC_SCLN: { name: 'Ų', title: 'LT_UOGO' },
  KC_QUOT: { name: 'Ė', title: 'LT_EDOT' },
  KC_NUHS: { name: 'Q', title: 'LT_Q' },
  // Row 4
  KC_NUBS: { name: '>\n<', title: 'LT_LABK' },
  KC_Z: { name: 'Z', title: 'LT_Z' },
  KC_X: { name: 'Ū', title: 'LT_UMAC' },
  KC_C: { name: 'C', title: 'LT_C' },
  KC_V: { name: 'V', title: 'LT_V' },
  KC_B: { name: 'B', title: 'LT_B' },
  KC_N: { name: 'N', title: 'LT_N' },
  KC_M: { name: 'M', title: 'LT_M' },
  KC_COMM: { name: 'Č', title: 'LT_CCAR' },
  KC_DOT: { name: 'F', title: 'LT_F' },
  KC_SLSH: { name: 'Ę', title: 'LT_EOGO' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ + │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', title: 'LT_TILD' },
  KC_TILD: { name: '~', title: 'LT_TILD' },
  'S(KC_1)': { name: '1', title: 'LT_1' },
  KC_EXLM: { name: '1', title: 'LT_1' },
  'S(KC_2)': { name: '2', title: 'LT_2' },
  KC_AT: { name: '2', title: 'LT_2' },
  'S(KC_3)': { name: '3', title: 'LT_3' },
  KC_HASH: { name: '3', title: 'LT_3' },
  'S(KC_4)': { name: '4', title: 'LT_4' },
  KC_DLR: { name: '4', title: 'LT_4' },
  'S(KC_5)': { name: '5', title: 'LT_5' },
  KC_PERC: { name: '5', title: 'LT_5' },
  'S(KC_6)': { name: '6', title: 'LT_6' },
  KC_CIRC: { name: '6', title: 'LT_6' },
  'S(KC_7)': { name: '7', title: 'LT_7' },
  KC_AMPR: { name: '7', title: 'LT_7' },
  'S(KC_8)': { name: '8', title: 'LT_8' },
  KC_ASTR: { name: '8', title: 'LT_8' },
  'S(KC_9)': { name: '9', title: 'LT_9' },
  KC_LPRN: { name: '9', title: 'LT_9' },
  'S(KC_0)': { name: '0', title: 'LT_0' },
  KC_RPRN: { name: '0', title: 'LT_0' },
  'S(KC_MINS)': { name: '+', title: 'LT_PLUS' },
  KC_UNDS: { name: '+', title: 'LT_PLUS' },
  // Row 4
  'S(KC_NUBS)': { name: '>', title: 'LT_RABK' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ´ │ @ │ _ │ # │ $ │ § │ ^ │ & │ * │ [ │ ] │ ' │ % │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ € │   │   │   │   │   │   │   │ { │ } │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ " │ | │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ – │   │   │   │   │   │   │   │ „ │ “ │ \ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_GRV)': { name: '´', title: 'LT_ACUT' },
  'ALGR(KC_1)': { name: '@', title: 'LT_AT' },
  'ALGR(KC_2)': { name: '_', title: 'LT_UNDS' },
  'ALGR(KC_3)': { name: '#', title: 'LT_HASH' },
  'ALGR(KC_4)': { name: '$', title: 'LT_DLR' },
  'ALGR(KC_5)': { name: '§', title: 'LT_SECT' },
  'ALGR(KC_6)': { name: '^', title: 'LT_CIRC' },
  'ALGR(KC_7)': { name: '&', title: 'LT_AMPR' },
  'ALGR(KC_8)': { name: '*', title: 'LT_ASTR' },
  'ALGR(KC_9)': { name: '[', title: 'LT_LBRC' },
  'ALGR(KC_0)': { name: ']', title: 'LT_RBRC' },
  'ALGR(KC_MINS)': { name: "'", title: 'LT_QUOT' },
  'ALGR(KC_EQL)': { name: '%', title: 'LT_PERC' },
  // Row 2
  'ALGR(KC_E)': { name: '€', title: 'LT_EURO' },
  'ALGR(KC_LBRC)': { name: '{', title: 'LT_LCBR' },
  'ALGR(KC_RBRC)': { name: '}', title: 'LT_RCBR' },
  // Row 3
  'ALGR(KC_QUOT)': { name: '"', title: 'LT_DQUO' },
  'ALGR(KC_NUHS)': { name: '|', title: 'LT_PIPE' },
  // Row 4
  'ALGR(KC_NUBS)': { name: '–', title: 'LT_NDSH' },
  'ALGR(KC_COMM)': { name: '„', title: 'LT_DLQU' },
  'ALGR(KC_DOT)': { name: '“', title: 'LT_LDQU' },
  'ALGR(KC_SLSH)': { name: '\\', title: 'LT_BSLS' },

  /* Other keys */
  KC_BSLS: { name: 'Q', title: '' },
  'S(KC_BSLS)': { name: 'Q', title: '' },
  KC_PLUS: { name: 'X', title: 'S(LT_X) (capital X)' },
  KC_LCBR: { name: 'Į', title: 'S(LT_IOGO) (capital Į)' },
  KC_RCBR: { name: 'W', title: 'S(LT_W) (capital W)' },
  KC_LT: { name: 'Č', title: 'S(LT_CCAR) (capital Č)' },
  KC_GT: { name: 'F', title: 'S(LT_F) (capital F)' },
  KC_COLN: { name: 'Ų', title: 'S(LT_UOGO) (capital Ų)' },
  KC_PIPE: { name: 'Q', title: 'LT_Q (capital Q)' },
  KC_QUES: { name: 'Ę', title: 'S(LT_EOGO) (capital Ę)' },
  KC_DQUO: { name: 'Ė', title: 'S(LT_EDOT) (capital Ė)' },

  SC_LSPO: { name: 'LS / 9', title: 'Left Shift when held, 9 when tapped' },
  SC_RSPC: { name: 'RS / 0', title: 'Right Shift when held, 0 when tapped' },
  SC_LCPO: { name: 'LC / 9', title: 'Left Control when held, 9 when tapped' },
  SC_RCPC: { name: 'RC / 0', title: 'Right Control when held, 0 when tapped' },
  SC_LAPO: { name: 'LA / 9', title: 'Left Alt when held, 9 when tapped' },
  SC_RAPC: { name: 'RA / 0', title: 'Right Alt when held, 0 when tapped' },

  QK_GESC: {
    name: '`/~\nEsc',
    title: 'Esc normally, but ` when GUI is active or ~ when Shift is active'
  }
};
