/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ ; │ ς │ Ε │ Ρ │ Τ │ Υ │ Θ │ Ι │ Ο │ Π │ [ │ ] │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ Α │ Σ │ Δ │ Φ │ Γ │ Η │ Ξ │ Κ │ Λ │ ΄ │ ' │ \ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │ Ζ │ Χ │ Ψ │ Ω │ Β │ Ν │ Μ │ , │ . │ / │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '~\n`', title: 'GR_GRV' },
  KC_1: { name: '!\n1', title: 'GR_1' },
  KC_2: { name: '@\n2', title: 'GR_2' },
  KC_3: { name: '#\n3', title: 'GR_3' },
  KC_4: { name: '$\n4', title: 'GR_4' },
  KC_5: { name: '%\n5', title: 'GR_5' },
  KC_6: { name: '^\n6', title: 'GR_6' },
  KC_7: { name: '&\n7', title: 'GR_7' },
  KC_8: { name: '*\n8', title: 'GR_8' },
  KC_9: { name: '(\n9', title: 'GR_9' },
  KC_0: { name: ')\n0', title: 'GR_0' },
  KC_MINS: { name: '_\n-', title: 'GR_MINS' },
  KC_EQL: { name: '+\n=', title: 'GR_EQL' },
  // Row 2
  KC_Q: { name: ':\n;', title: 'GR_SCLN' },
  KC_W: { name: '΅\nς', title: 'GR_FSIG' },
  KC_E: { name: 'Ε', title: 'GR_EPSL' },
  KC_R: { name: 'Ρ', title: 'GR_RHO' },
  KC_T: { name: 'Τ', title: 'GR_TAU' },
  KC_Y: { name: 'Υ', title: 'GR_UPSL' },
  KC_U: { name: 'Θ', title: 'GR_THET' },
  KC_I: { name: 'Ι', title: 'GR_IOTA' },
  KC_O: { name: 'Ο', title: 'GR_OMCR' },
  KC_P: { name: 'Π', title: 'GR_PI' },
  KC_LBRC: { name: '{\n[', title: 'GR_LBRC' },
  KC_RBRC: { name: '}\n]', title: 'GR_RBRC' },
  // Row 3
  KC_A: { name: 'Α', title: 'GR_ALPH' },
  KC_S: { name: 'Σ', title: 'GR_SIGM' },
  KC_D: { name: 'Δ', title: 'GR_DELT' },
  KC_F: { name: 'Φ', title: 'GR_PHI' },
  KC_G: { name: 'Γ', title: 'GR_GAMM' },
  KC_H: { name: 'Η', title: 'GR_ETA' },
  KC_J: { name: 'Ξ', title: 'GR_XI' },
  KC_K: { name: 'Κ', title: 'GR_KAPP' },
  KC_L: { name: 'Λ', title: 'GR_LAMB' },
  KC_SCLN: { name: '¨\n΄', title: 'GR_TONS (dead)' },
  KC_QUOT: { name: '"\n\'', title: 'GR_QUOT' },
  KC_NUHS: { name: '|\n\\', title: 'GR_BSLS' },
  // Row 4
  KC_Z: { name: 'Ζ', title: 'GR_ZETA' },
  KC_X: { name: 'Χ', title: 'GR_CHI' },
  KC_C: { name: 'Ψ', title: 'GR_PSI' },
  KC_V: { name: 'Ω', title: 'GR_OMEG' },
  KC_B: { name: 'Β', title: 'GR_BETA' },
  KC_N: { name: 'Ν', title: 'GR_NU' },
  KC_M: { name: 'Μ', title: 'GR_MU' },
  KC_COMM: { name: '<\n,', title: 'GR_COMM' },
  KC_DOT: { name: '>\n.', title: 'GR_DOT' },
  KC_SLSH: { name: '?\n/', title: 'GR_SLSH' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │ ! │ @ │ # │ $ │ % │ ^ │ & │ * │ ( │ ) │ _ │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ : │ ΅ │   │   │   │   │   │   │   │   │ { │ } │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │ ¨ │ " │ | │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │   │   │   │   │ < │ > │ ? │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', title: 'GR_TILD' },
  KC_TILD: { name: '~', title: 'GR_TILD' },
  'S(KC_1)': { name: '!', title: 'GR_EXLM' },
  KC_EXLM: { name: '!', title: 'GR_EXLM' },
  'S(KC_2)': { name: '@', title: 'GR_AT' },
  KC_AT: { name: '@', title: 'GR_AT' },
  'S(KC_3)': { name: '#', title: 'GR_HASH' },
  KC_HASH: { name: '#', title: 'GR_HASH' },
  'S(KC_4)': { name: '$', title: 'GR_DLR' },
  KC_DLR: { name: '$', title: 'GR_DLR' },
  'S(KC_5)': { name: '%', title: 'GR_PERC' },
  KC_PERC: { name: '%', title: 'GR_PERC' },
  'S(KC_6)': { name: '^', title: 'GR_CIRC' },
  KC_CIRC: { name: '^', title: 'GR_CIRC' },
  'S(KC_7)': { name: '&', title: 'GR_AMPR' },
  KC_AMPR: { name: '&', title: 'GR_AMPR' },
  'S(KC_8)': { name: '*', title: 'GR_ASTR' },
  KC_ASTR: { name: '*', title: 'GR_ASTR' },
  'S(KC_9)': { name: '(', title: 'GR_LPRN' },
  KC_LPRN: { name: '(', title: 'GR_LPRN' },
  'S(KC_0)': { name: ')', title: 'GR_RPRN' },
  KC_RPRN: { name: ')', title: 'GR_RPRN' },
  'S(KC_MINS)': { name: '_', title: 'GR_UNDS' },
  KC_UNDS: { name: '_', title: 'GR_UNDS' },
  'S(KC_EQL)': { name: '+', title: 'GR_PLUS' },
  KC_PLUS: { name: '+', title: 'GR_PLUS' },
  // Row 2
  'S(KC_Q)': { name: ':', title: 'GR_COLN' },
  'S(KC_W)': { name: '΅', title: 'GR_DIAT (dead)' },
  'S(KC_LBRC)': { name: '{', title: 'GR_LCBR' },
  KC_LCBR: { name: '{', title: 'GR_LCBR' },
  'S(KC_RBRC)': { name: '}', title: 'GR_RCBR' },
  KC_RCBR: { name: '}', title: 'GR_RCBR' },
  // Row 3
  'S(KC_SCLN)': { name: '¨', title: 'GR_DIAE (dead)' },
  KC_COLN: { name: '¨', title: 'GR_DIAE (dead)' },
  'S(KC_QUOT)': { name: '"', title: 'GR_DQUO' },
  KC_DQUO: { name: '"', title: 'GR_DQUO' },
  'S(KC_NUHS)': { name: '|', title: 'GR_PIPE' },
  // Row 4
  'S(KC_COMM)': { name: '<', title: 'GR_LABK' },
  KC_LT: { name: '<', title: 'GR_LABK' },
  'S(KC_DOT)': { name: '>', title: 'GR_RABK' },
  KC_GT: { name: '>', title: 'GR_RABK' },
  'S(KC_SLSH)': { name: '?', title: 'GR_QUES' },
  KC_QUES: { name: '?', title: 'GR_QUES' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │   │ ² │ ³ │ £ │ § │ ¶ │   │ ¤ │ ¦ │ ° │ ± │ ½ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ € │ ® │   │ ¥ │   │   │   │   │ « │ » │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │ ¬ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │ © │   │   │   │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_2)': { name: '²', title: 'GR_SUP2' },
  'ALGR(KC_3)': { name: '³', title: 'GR_SUP3' },
  'ALGR(KC_4)': { name: '£', title: 'GR_PND' },
  'ALGR(KC_5)': { name: '§', title: 'GR_SECT' },
  'ALGR(KC_6)': { name: '¶', title: 'GR_PILC' },
  'ALGR(KC_8)': { name: '¤', title: 'GR_CURR' },
  'ALGR(KC_9)': { name: '¦', title: 'GR_BRKP' },
  'ALGR(KC_0)': { name: '°', title: 'GR_DEG' },
  'ALGR(KC_MINS)': { name: '±', title: 'GR_PLMN' },
  'ALGR(KC_EQL)': { name: '½', title: 'GR_HALF' },
  // Row 2
  'ALGR(KC_E)': { name: '€', title: 'GR_EURO' },
  'ALGR(KC_R)': { name: '®', title: 'GR_REGD' },
  'ALGR(KC_Y)': { name: '¥', title: 'GR_YEN' },
  'ALGR(KC_LBRC)': { name: '«', title: 'GR_LDAQ' },
  'ALGR(KC_RBRC)': { name: '»', title: 'GR_RDAQ' },
  // Row 3
  'ALGR(KC_NUHS)': { name: '¬', title: 'GR_NOT' },
  // Row 4
  'ALGR(KC_C)': { name: '©', title: 'GR_COPY' },

  /* Other keys */
  KC_BSLS: { name: '|\n\\', title: '' },
  'S(KC_BSLS)': { name: '|', title: '' },
  KC_NUBS: { name: '|\n\\', title: '' },
  'S(KC_NUBS)': { name: '|', title: '' },
  KC_PIPE: { name: '|', title: 'GR_PIPE' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: '`/~\nEsc',
    title: 'Esc normally, but ` when GUI is active or ~ when Shift is active'
  }
};
