/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ° │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ Ö │ - │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ Ð │ ' │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ Æ │ ´ │ + │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ Þ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '¨\n°', title: 'IS_RNGA (dead)' },
  KC_1: { name: '!\n1', title: 'IS_1' },
  KC_2: { name: '"\n2', title: 'IS_2' },
  KC_3: { name: '#\n3', title: 'IS_3' },
  KC_4: { name: '$\n4', title: 'IS_4' },
  KC_5: { name: '%\n5', title: 'IS_5' },
  KC_6: { name: '&\n6', title: 'IS_6' },
  KC_7: { name: '/\n7', title: 'IS_7' },
  KC_8: { name: '(\n8', title: 'IS_8' },
  KC_9: { name: ')\n9', title: 'IS_9' },
  KC_0: { name: '=\n0', title: 'IS_0' },
  KC_MINS: { name: 'Ö', title: 'IS_ODIA' },
  KC_EQL: { name: '_\n-', title: 'IS_MINS' },
  // Row 2
  KC_Q: { name: 'Q', title: 'IS_Q' },
  KC_W: { name: 'W', title: 'IS_W' },
  KC_E: { name: 'E', title: 'IS_E' },
  KC_R: { name: 'R', title: 'IS_R' },
  KC_T: { name: 'T', title: 'IS_T' },
  KC_Y: { name: 'Y', title: 'IS_Y' },
  KC_U: { name: 'U', title: 'IS_U' },
  KC_I: { name: 'I', title: 'IS_I' },
  KC_O: { name: 'O', title: 'IS_O' },
  KC_P: { name: 'P', title: 'IS_P' },
  KC_LBRC: { name: 'Ð', title: 'IS_ETH' },
  KC_RBRC: { name: "?\n'", title: 'IS_QUOT' },
  // Row 3
  KC_A: { name: 'A', title: 'IS_A' },
  KC_S: { name: 'S', title: 'IS_S' },
  KC_D: { name: 'D', title: 'IS_D' },
  KC_F: { name: 'F', title: 'IS_F' },
  KC_G: { name: 'G', title: 'IS_G' },
  KC_H: { name: 'H', title: 'IS_H' },
  KC_J: { name: 'J', title: 'IS_J' },
  KC_K: { name: 'K', title: 'IS_K' },
  KC_L: { name: 'L', title: 'IS_L' },
  KC_SCLN: { name: 'Æ', title: 'IS_AE' },
  KC_QUOT: { name: '´', title: 'IS_ACUT (dead)' },
  KC_NUHS: { name: '*\n+', title: 'IS_PLUS' },
  // Row 4
  KC_NUBS: { name: '>\n<', title: 'IS_LABK' },
  KC_Z: { name: 'Z', title: 'IS_Z' },
  KC_X: { name: 'X', title: 'IS_X' },
  KC_C: { name: 'C', title: 'IS_C' },
  KC_V: { name: 'V', title: 'IS_V' },
  KC_B: { name: 'B', title: 'IS_B' },
  KC_N: { name: 'N', title: 'IS_N' },
  KC_M: { name: 'M', title: 'IS_M' },
  KC_COMM: { name: ';\n,', title: 'IS_COMM' },
  KC_DOT: { name: ':\n.', title: 'IS_DOT' },
  KC_SLSH: { name: 'Þ', title: 'IS_THRN' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ¨ │ ! │ " │ # │ $ │ % │ & │ / │ ( │ ) │ = │   │ _ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │ ? │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │ * │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │ ; │ : │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '¨', title: 'IS_DIAE (dead)' },
  KC_TILD: { name: '¨', title: 'IS_DIAE (dead)' },
  'S(KC_1)': { name: '!', title: 'IS_EXLM' },
  KC_EXLM: { name: '!', title: 'IS_EXLM' },
  'S(KC_2)': { name: '"', title: 'IS_DQUO' },
  KC_AT: { name: '"', title: 'IS_DQUO' },
  'S(KC_3)': { name: '#', title: 'IS_HASH' },
  KC_HASH: { name: '#', title: 'IS_HASH' },
  'S(KC_4)': { name: '$', title: 'IS_DLR' },
  KC_DLR: { name: '$', title: 'IS_DLR' },
  'S(KC_5)': { name: '%', title: 'IS_PERC' },
  KC_PERC: { name: '%', title: 'IS_PERC' },
  'S(KC_6)': { name: '&', title: 'IS_AMPR' },
  KC_CIRC: { name: '&', title: 'IS_AMPR' },
  'S(KC_7)': { name: '/', title: 'IS_SLSH' },
  KC_AMPR: { name: '/', title: 'IS_SLSH' },
  'S(KC_8)': { name: '(', title: 'IS_LPRN' },
  KC_ASTR: { name: '(', title: 'IS_LPRN' },
  'S(KC_9)': { name: ')', title: 'IS_RPRN' },
  KC_LPRN: { name: ')', title: 'IS_RPRN' },
  'S(KC_0)': { name: '=', title: 'IS_EQL' },
  KC_RPRN: { name: '=', title: 'IS_EQL' },
  'S(KC_EQL)': { name: '_', title: 'IS_UNDS' },
  KC_PLUS: { name: '_', title: 'IS_UNDS' },
  // Row 2
  'S(KC_RBRC)': { name: '?', title: 'IS_QUES' },
  KC_RCBR: { name: '?', title: 'IS_QUES' },
  // Row 3
  'S(KC_NUHS)': { name: '*', title: 'IS_ASTR' },
  // Row 4
  'S(KC_NUBS)': { name: '>', title: 'IS_RABK' },
  'S(KC_COMM)': { name: ';', title: 'IS_SCLN' },
  KC_LT: { name: ';', title: 'IS_SCLN' },
  'S(KC_DOT)': { name: ':', title: 'IS_COLN' },
  KC_GT: { name: ':', title: 'IS_COLN' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ° │   │   │   │   │   │   │ { │ [ │ ] │ } │ \ │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ @ │   │ € │   │   │   │   │   │   │   │   │ ~ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ ^ │ ` │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ | │   │   │   │   │   │   │ µ │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_GRV)': { name: '°', title: 'IS_DEG' },
  'ALGR(KC_7)': { name: '{', title: 'IS_LCBR' },
  'ALGR(KC_8)': { name: '[', title: 'IS_LBRC' },
  'ALGR(KC_9)': { name: ']', title: 'IS_RBRC' },
  'ALGR(KC_0)': { name: '}', title: 'IS_RCBR' },
  'ALGR(KC_MINS)': { name: '\\', title: 'IS_BSLS' },
  // Row 2
  'ALGR(KC_Q)': { name: '@', title: 'IS_AT' },
  'ALGR(KC_E)': { name: '€', title: 'IS_EURO' },
  'ALGR(KC_RBRC)': { name: '~', title: 'IS_TILD' },
  // Row 3
  'ALGR(KC_QUOT)': { name: '^', title: 'IS_CIRC (dead)' },
  'ALGR(KC_NUHS)': { name: '`', title: 'IS_GRV (dead)' },
  // Row 4
  'ALGR(KC_NUBS)': { name: '|', title: 'IS_PIPE' },
  'ALGR(KC_M)': { name: 'µ', title: 'IS_MICR' },

  /* Other keys */
  KC_BSLS: { name: '*\n+', title: '' },
  'S(KC_BSLS)': { name: '*', title: '' },
  KC_UNDS: { name: 'Ö', title: 'S(IS_ODIA) (capital Ö)' },
  KC_LCBR: { name: 'Ð', title: 'S(IS_ETH) (capital Ð)' },
  KC_COLN: { name: 'Æ', title: 'S(IS_AE) (capital Æ)' },
  KC_PIPE: { name: '*', title: 'IS_ASTR' },
  KC_QUES: { name: 'Þ', title: 'S(IS_THRN) (capital Þ)' },
  KC_DQUO: { name: '´', title: 'S(IS_ACUT)' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / =', title: 'Right Shift when held, = when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / =', title: 'Right Control when held, = when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / =', title: 'Right Alt when held, = when tapped' },

  QK_GESC: {
    name: '°/¨\nEsc',
    title: 'Esc normally, but ° when GUI is active or ¨ when Shift is active'
  }
};
