/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ [ │ ] │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ; │ ' │ # │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ \ │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ / │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '¬\n`', title: 'UK_GRV' },
  KC_1: { name: '!\n1', title: 'UK_1' },
  KC_2: { name: '"\n2', title: 'UK_2' },
  KC_3: { name: '£\n3', title: 'UK_3' },
  KC_4: { name: '$\n4', title: 'UK_4' },
  KC_5: { name: '%\n5', title: 'UK_5' },
  KC_6: { name: '^\n6', title: 'UK_6' },
  KC_7: { name: '&\n7', title: 'UK_7' },
  KC_8: { name: '*\n8', title: 'UK_8' },
  KC_9: { name: '(\n9', title: 'UK_9' },
  KC_0: { name: ')\n0', title: 'UK_0' },
  KC_MINS: { name: '_\n-', title: 'UK_MINS' },
  KC_EQL: { name: '+\n=', title: 'UK_EQL' },
  // Row 2
  KC_Q: { name: 'Q', title: 'UK_Q' },
  KC_W: { name: 'W', title: 'UK_W' },
  KC_E: { name: 'E', title: 'UK_E' },
  KC_R: { name: 'R', title: 'UK_R' },
  KC_T: { name: 'T', title: 'UK_T' },
  KC_Y: { name: 'Y', title: 'UK_Y' },
  KC_U: { name: 'U', title: 'UK_U' },
  KC_I: { name: 'I', title: 'UK_I' },
  KC_O: { name: 'O', title: 'UK_O' },
  KC_P: { name: 'P', title: 'UK_P' },
  KC_LBRC: { name: '{\n[', title: 'UK_LBRC' },
  KC_RBRC: { name: '}\n]', title: 'UK_RBRC' },
  // Row 3
  KC_A: { name: 'A', title: 'UK_A' },
  KC_S: { name: 'S', title: 'UK_S' },
  KC_D: { name: 'D', title: 'UK_D' },
  KC_F: { name: 'F', title: 'UK_F' },
  KC_G: { name: 'G', title: 'UK_G' },
  KC_H: { name: 'H', title: 'UK_H' },
  KC_J: { name: 'J', title: 'UK_J' },
  KC_K: { name: 'K', title: 'UK_K' },
  KC_L: { name: 'L', title: 'UK_L' },
  KC_SCLN: { name: ':\n;', title: 'UK_SCLN' },
  KC_QUOT: { name: "@\n'", title: 'UK_QUOT' },
  KC_NUHS: { name: '~\n#', title: 'UK_HASH' },
  // Row 4
  KC_NUBS: { name: '|\n\\', title: 'UK_BSLS' },
  KC_Z: { name: 'Z', title: 'UK_Z' },
  KC_X: { name: 'X', title: 'UK_X' },
  KC_C: { name: 'C', title: 'UK_C' },
  KC_V: { name: 'V', title: 'UK_V' },
  KC_B: { name: 'B', title: 'UK_B' },
  KC_N: { name: 'N', title: 'UK_N' },
  KC_M: { name: 'M', title: 'UK_M' },
  KC_COMM: { name: '<\n,', title: 'UK_COMM' },
  KC_DOT: { name: '>\n.', title: 'UK_DOT' },
  KC_SLSH: { name: '?\n/', title: 'UK_SLSH' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ¬ │ ! │ " │ £ │ $ │ % │ ^ │ & │ * │ ( │ ) │ _ │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ { │ } │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │ : │ @ │ ~ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ | │   │   │   │   │   │   │   │ < │ > │ ? │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '¬', title: 'UK_NOT' },
  KC_TILD: { name: '¬', title: 'UK_NOT' },
  'S(KC_1)': { name: '!', title: 'UK_EXLM' },
  KC_EXLM: { name: '!', title: 'UK_EXLM' },
  'S(KC_2)': { name: '"', title: 'UK_DQUO' },
  KC_AT: { name: '"', title: 'UK_DQUO' },
  'S(KC_3)': { name: '£', title: 'UK_PND' },
  KC_HASH: { name: '£', title: 'UK_PND' },
  'S(KC_4)': { name: '$', title: 'UK_DLR' },
  KC_DLR: { name: '$', title: 'UK_DLR' },
  'S(KC_5)': { name: '%', title: 'UK_PERC' },
  KC_PERC: { name: '%', title: 'UK_PERC' },
  'S(KC_6)': { name: '^', title: 'UK_CIRC' },
  KC_CIRC: { name: '^', title: 'UK_CIRC' },
  'S(KC_7)': { name: '&', title: 'UK_AMPR' },
  KC_AMPR: { name: '&', title: 'UK_AMPR' },
  'S(KC_8)': { name: '*', title: 'UK_ASTR' },
  KC_ASTR: { name: '*', title: 'UK_ASTR' },
  'S(KC_9)': { name: '(', title: 'UK_LPRN' },
  KC_LPRN: { name: '(', title: 'UK_LPRN' },
  'S(KC_0)': { name: ')', title: 'UK_RPRN' },
  KC_RPRN: { name: ')', title: 'UK_RPRN' },
  'S(KC_MINS)': { name: '_', title: 'UK_UNDS' },
  KC_UNDS: { name: '_', title: 'UK_UNDS' },
  'S(KC_EQL)': { name: '+', title: 'UK_PLUS' },
  KC_PLUS: { name: '+', title: 'UK_PLUS' },
  // Row 2
  'S(KC_LBRC)': { name: '{', title: 'UK_LCBR' },
  KC_LCBR: { name: '{', title: 'UK_LCBR' },
  'S(KC_RBRC)': { name: '}', title: 'UK_RCBR' },
  KC_RCBR: { name: '}', title: 'UK_RCBR' },
  // Row 3
  'S(KC_SCLN)': { name: ':', title: 'UK_COLN' },
  KC_COLN: { name: ':', title: 'UK_COLN' },
  'S(KC_QUOT)': { name: '@', title: 'UK_AT' },
  KC_DQUO: { name: '@', title: 'UK_AT' },
  'S(KC_NUHS)': { name: '~', title: 'UK_TILD' },
  // Row 4
  'S(KC_NUBS)': { name: '|', title: 'UK_PIPE' },
  'S(KC_COMM)': { name: '<', title: 'UK_LABK' },
  KC_LT: { name: '<', title: 'UK_LABK' },
  'S(KC_DOT)': { name: '>', title: 'UK_RABK' },
  KC_GT: { name: '>', title: 'UK_RABK' },
  'S(KC_SLSH)': { name: '?', title: 'UK_QUES' },
  KC_QUES: { name: '?', title: 'UK_QUES' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ¦ │   │   │   │ € │   │   │   │   │   │   │   │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ É │   │   │   │ Ú │ Í │ Ó │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ Á │   │   │   │   │   │   │   │   │   │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_GRV)': { name: '¦', title: 'UK_BRKP' },
  'ALGR(KC_4)': { name: '€', title: 'UK_EURO' },
  // Row 2
  'ALGR(KC_E)': { name: 'É', title: 'UK_EACU' },
  'ALGR(KC_U)': { name: 'Ú', title: 'UK_UACU' },
  'ALGR(KC_I)': { name: 'Í', title: 'UK_IACU' },
  'ALGR(KC_O)': { name: 'Ó', title: 'UK_OACU' },
  // Row 3
  'ALGR(KC_A)': { name: 'Á', title: 'UK_AACU' },

  /* Other keys */
  KC_BSLS: { name: '~\n#', title: '' },
  'S(KC_BSLS)': { name: '~', title: '' },
  KC_PIPE: { name: '~', title: 'UK_TILD' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: '`/¬\nEsc',
    title: 'Esc normally, but ` when GUI is active or ¬ when Shift is active'
  }
};
