/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ [ │ ] │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ; │ ' │ \ │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ \ │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ / │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '~\n`', title: 'LV_GRV' },
  KC_1: { name: '!\n1', title: 'LV_1' },
  KC_2: { name: '@\n2', title: 'LV_2' },
  KC_3: { name: '#\n3', title: 'LV_3' },
  KC_4: { name: '$\n4', title: 'LV_4' },
  KC_5: { name: '%\n5', title: 'LV_5' },
  KC_6: { name: '^\n6', title: 'LV_6' },
  KC_7: { name: '&\n7', title: 'LV_7' },
  KC_8: { name: '*\n8', title: 'LV_8' },
  KC_9: { name: '(\n9', title: 'LV_9' },
  KC_0: { name: ')\n0', title: 'LV_0' },
  KC_MINS: { name: '_\n-', title: 'LV_MINS' },
  KC_EQL: { name: '+\n=', title: 'LV_EQL' },
  // Row 2
  KC_Q: { name: 'Q', title: 'LV_Q' },
  KC_W: { name: 'W', title: 'LV_W' },
  KC_E: { name: 'E', title: 'LV_E' },
  KC_R: { name: 'R', title: 'LV_R' },
  KC_T: { name: 'T', title: 'LV_T' },
  KC_Y: { name: 'Y', title: 'LV_Y' },
  KC_U: { name: 'U', title: 'LV_U' },
  KC_I: { name: 'I', title: 'LV_I' },
  KC_O: { name: 'O', title: 'LV_O' },
  KC_P: { name: 'P', title: 'LV_P' },
  KC_LBRC: { name: '{\n[', title: 'LV_LBRC' },
  KC_RBRC: { name: '}\n]', title: 'LV_RBRC' },
  // Row 3
  KC_A: { name: 'A', title: 'LV_A' },
  KC_S: { name: 'S', title: 'LV_S' },
  KC_D: { name: 'D', title: 'LV_D' },
  KC_F: { name: 'F', title: 'LV_F' },
  KC_G: { name: 'G', title: 'LV_G' },
  KC_H: { name: 'H', title: 'LV_H' },
  KC_J: { name: 'J', title: 'LV_J' },
  KC_K: { name: 'K', title: 'LV_K' },
  KC_L: { name: 'L', title: 'LV_L' },
  KC_SCLN: { name: ':\n;', title: 'LV_SCLN' },
  KC_QUOT: { name: '"\n\'', title: 'LV_QUOT (dead)' },
  KC_NUHS: { name: '|\n\\', title: 'LV_BSLS' },
  // Row 4
  KC_NUBS: { name: '\\', title: 'LV_NUBS' },
  KC_Z: { name: 'Z', title: 'LV_Z' },
  KC_X: { name: 'X', title: 'LV_X' },
  KC_C: { name: 'C', title: 'LV_C' },
  KC_V: { name: 'V', title: 'LV_V' },
  KC_B: { name: 'B', title: 'LV_B' },
  KC_N: { name: 'N', title: 'LV_N' },
  KC_M: { name: 'M', title: 'LV_M' },
  KC_COMM: { name: '<\n,', title: 'LV_COMM' },
  KC_DOT: { name: '>\n.', title: 'LV_DOT' },
  KC_SLSH: { name: '?\n/', title: 'LV_SLSH' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │ ! │ @ │ # │ $ │ % │ ^ │ & │ * │ ( │ ) │ _ │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ { │ } │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │ : │ " │ | │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │   │   │   │   │ < │ > │ ? │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', title: 'LV_TILD' },
  KC_TILD: { name: '~', title: 'LV_TILD' },
  'S(KC_1)': { name: '!', title: 'LV_EXLM' },
  KC_EXLM: { name: '!', title: 'LV_EXLM' },
  'S(KC_2)': { name: '@', title: 'LV_AT' },
  KC_AT: { name: '@', title: 'LV_AT' },
  'S(KC_3)': { name: '#', title: 'LV_HASH' },
  KC_HASH: { name: '#', title: 'LV_HASH' },
  'S(KC_4)': { name: '$', title: 'LV_DLR' },
  KC_DLR: { name: '$', title: 'LV_DLR' },
  'S(KC_5)': { name: '%', title: 'LV_PERC' },
  KC_PERC: { name: '%', title: 'LV_PERC' },
  'S(KC_6)': { name: '^', title: 'LV_CIRC' },
  KC_CIRC: { name: '^', title: 'LV_CIRC' },
  'S(KC_7)': { name: '&', title: 'LV_AMPR' },
  KC_AMPR: { name: '&', title: 'LV_AMPR' },
  'S(KC_8)': { name: '*', title: 'LV_ASTR' },
  KC_ASTR: { name: '*', title: 'LV_ASTR' },
  'S(KC_9)': { name: '(', title: 'LV_LPRN' },
  KC_LPRN: { name: '(', title: 'LV_LPRN' },
  'S(KC_0)': { name: ')', title: 'LV_RPRN' },
  KC_RPRN: { name: ')', title: 'LV_RPRN' },
  'S(KC_MINS)': { name: '_', title: 'LV_UNDS' },
  KC_UNDS: { name: '_', title: 'LV_UNDS' },
  'S(KC_EQL)': { name: '+', title: 'LV_PLUS' },
  KC_PLUS: { name: '+', title: 'LV_PLUS' },
  // Row 2
  'S(KC_LBRC)': { name: '{', title: 'LV_LCBR' },
  KC_LCBR: { name: '{', title: 'LV_LCBR' },
  'S(KC_RBRC)': { name: '}', title: 'LV_RCBR' },
  KC_RCBR: { name: '}', title: 'LV_RCBR' },
  // Row 3
  'S(KC_SCLN)': { name: ':', title: 'LV_COLN' },
  KC_COLN: { name: ':', title: 'LV_COLN' },
  'S(KC_QUOT)': { name: '"', title: 'LV_DQUO (dead)' },
  KC_DQUO: { name: '"', title: 'LV_DQUO (dead)' },
  'S(KC_NUHS)': { name: '|', title: 'LV_PIPE' },
  // Row 4
  'S(KC_COMM)': { name: '<', title: 'LV_LABK' },
  KC_LT: { name: '<', title: 'LV_LABK' },
  'S(KC_DOT)': { name: '>', title: 'LV_RABK' },
  KC_GT: { name: '>', title: 'LV_RABK' },
  'S(KC_SLSH)': { name: '?', title: 'LV_QUES' },
  KC_QUES: { name: '?', title: 'LV_QUES' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ - │   │ « │ » │ € │   │ ’ │   │   │   │   │ – │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │ Ē │ Ŗ │   │   │ Ū │ Ī │ Ō │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ Ā │ Š │   │   │ Ģ │   │   │ Ķ │ Ļ │   │ ´ │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │ Ž │   │ Č │   │   │ Ņ │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_GRV)': { name: 'Soft hyphen', title: 'LV_SHYP (soft hyphen)' },
  'ALGR(KC_1)': {
    name: 'No-break space',
    title: 'LV_NBSP (non-breaking space)'
  },
  'ALGR(KC_2)': { name: '«', title: 'LV_LDAQ' },
  'ALGR(KC_3)': { name: '»', title: 'LV_RDAQ' },
  'ALGR(KC_4)': { name: '€', title: 'LV_EURO' },
  'ALGR(KC_6)': { name: '’', title: 'LV_RSQU' },
  'ALGR(KC_MINS)': { name: '–', title: 'LV_NDSH' },
  // Row 2
  'ALGR(KC_E)': { name: 'Ē', title: 'LV_EMAC' },
  'ALGR(KC_R)': { name: 'Ŗ', title: 'LV_RCED' },
  'ALGR(KC_U)': { name: 'Ū', title: 'LV_UMAC' },
  'ALGR(KC_I)': { name: 'Ī', title: 'LV_IMAC' },
  'ALGR(KC_O)': { name: 'Ō', title: 'LV_OMAC' },
  // Row 3
  'ALGR(KC_A)': { name: 'Ā', title: 'LV_AMAC' },
  'ALGR(KC_S)': { name: 'Š', title: 'LV_SCAR' },
  'ALGR(KC_G)': { name: 'Ģ', title: 'LV_GCED' },
  'ALGR(KC_K)': { name: 'Ķ', title: 'LV_KCED' },
  'ALGR(KC_L)': { name: 'Ļ', title: 'LV_LCED' },
  'ALGR(KC_QUOT)': { name: '´', title: 'LV_ACUT (dead)' },
  // Row 4
  'ALGR(KC_Z)': { name: 'Ž', title: 'LV_ZCAR' },
  'ALGR(KC_C)': { name: 'Č', title: 'LV_CCAR' },
  'ALGR(KC_N)': { name: 'Ņ', title: 'LV_NCED' },

  /* Shift+AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │   │   │   │ § │ ° │   │ ± │ × │   │   │ — │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │   │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │ ¨ │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │   │   │   │   │   │   │   │   │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(ALGR(KC_4))': { name: '§', title: 'LV_SECT' },
  'S(ALGR(KC_5))': { name: '°', title: 'LV_DEG' },
  'S(ALGR(KC_7))': { name: '±', title: 'LV_PLMN' },
  'S(ALGR(KC_8))': { name: '×', title: 'LV_MUL' },
  'S(ALGR(KC_MINS))': { name: '—', title: 'LV_MDSH' },
  // Row 3
  'S(ALGR(KC_QUOT))': { name: '¨', title: 'LV_DIAE (dead)' },

  /* Other keys */
  KC_BSLS: { name: '|\n\\', title: '' },
  'S(KC_BSLS)': { name: '|', title: '' },
  KC_PIPE: { name: '|', title: 'LV_PIPE' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: '`/~\nEsc',
    title: 'Esc normally, but ` when GUI is active or ~ when Shift is active'
  }
};
