/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ^ │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ ß │ ´ │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Z │ U │ I │ O │ P │ Ü │ + │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ Ö │ Ä │ # │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ < │ Y │ X │ C │ V │ B │ N │ M │ , │ . │ - │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '°\n^', title: 'DE_CIRC (dead)' },
  KC_1: { name: '!\n1', title: 'DE_1' },
  KC_2: { name: '"\n2', title: 'DE_2' },
  KC_3: { name: '§\n3', title: 'DE_3' },
  KC_4: { name: '$\n4', title: 'DE_4' },
  KC_5: { name: '%\n5', title: 'DE_5' },
  KC_6: { name: '&\n6', title: 'DE_6' },
  KC_7: { name: '/\n7', title: 'DE_7' },
  KC_8: { name: '(\n8', title: 'DE_8' },
  KC_9: { name: ')\n9', title: 'DE_9' },
  KC_0: { name: '=\n0', title: 'DE_0' },
  KC_MINS: { name: '?\nß', title: 'DE_SS' },
  KC_EQL: { name: '`\n´', title: 'DE_ACUT (dead)' },
  // Row 2
  KC_Q: { name: 'Q', title: 'DE_Q' },
  KC_W: { name: 'W', title: 'DE_W' },
  KC_E: { name: 'E', title: 'DE_E' },
  KC_R: { name: 'R', title: 'DE_R' },
  KC_T: { name: 'T', title: 'DE_T' },
  KC_Y: { name: 'Z', title: 'DE_Z' },
  KC_U: { name: 'U', title: 'DE_U' },
  KC_I: { name: 'I', title: 'DE_I' },
  KC_O: { name: 'O', title: 'DE_O' },
  KC_P: { name: 'P', title: 'DE_P' },
  KC_LBRC: { name: 'Ü', title: 'DE_UDIA' },
  KC_RBRC: { name: '*\n+', title: 'DE_PLUS' },
  // Row 3
  KC_A: { name: 'A', title: 'DE_A' },
  KC_S: { name: 'S', title: 'DE_S' },
  KC_D: { name: 'D', title: 'DE_D' },
  KC_F: { name: 'F', title: 'DE_F' },
  KC_G: { name: 'G', title: 'DE_G' },
  KC_H: { name: 'H', title: 'DE_H' },
  KC_J: { name: 'J', title: 'DE_J' },
  KC_K: { name: 'K', title: 'DE_K' },
  KC_L: { name: 'L', title: 'DE_L' },
  KC_SCLN: { name: 'Ö', title: 'DE_ODIA' },
  KC_QUOT: { name: 'Ä', title: 'DE_ADIA' },
  KC_NUHS: { name: "'\n#", title: 'DE_HASH' },
  // Row 4
  KC_NUBS: { name: '>\n<', title: 'DE_LABK' },
  KC_Z: { name: 'Y', title: 'DE_Y' },
  KC_X: { name: 'X', title: 'DE_X' },
  KC_C: { name: 'C', title: 'DE_C' },
  KC_V: { name: 'V', title: 'DE_V' },
  KC_B: { name: 'B', title: 'DE_B' },
  KC_N: { name: 'N', title: 'DE_N' },
  KC_M: { name: 'M', title: 'DE_M' },
  KC_COMM: { name: ';\n,', title: 'DE_COMM' },
  KC_DOT: { name: ':\n.', title: 'DE_DOT' },
  KC_SLSH: { name: '_\n-', title: 'DE_MINS' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ° │ ! │ " │ § │ $ │ % │ & │ / │ ( │ ) │ = │ ? │ ` │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │   │ * │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │ ' │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ > │   │   │   │   │   │   │   │ ; │ : │ _ │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '°', title: 'DE_DEG' },
  KC_TILD: { name: '°', title: 'DE_DEG' },
  'S(KC_1)': { name: '!', title: 'DE_EXLM' },
  KC_EXLM: { name: '!', title: 'DE_EXLM' },
  'S(KC_2)': { name: '"', title: 'DE_DQUO' },
  KC_AT: { name: '"', title: 'DE_DQUO' },
  'S(KC_3)': { name: '§', title: 'DE_SECT' },
  KC_HASH: { name: '§', title: 'DE_SECT' },
  'S(KC_4)': { name: '$', title: 'DE_DLR' },
  KC_DLR: { name: '$', title: 'DE_DLR' },
  'S(KC_5)': { name: '%', title: 'DE_PERC' },
  KC_PERC: { name: '%', title: 'DE_PERC' },
  'S(KC_6)': { name: '&', title: 'DE_AMPR' },
  KC_CIRC: { name: '&', title: 'DE_AMPR' },
  'S(KC_7)': { name: '/', title: 'DE_SLSH' },
  KC_AMPR: { name: '/', title: 'DE_SLSH' },
  'S(KC_8)': { name: '(', title: 'DE_LPRN' },
  KC_ASTR: { name: '(', title: 'DE_LPRN' },
  'S(KC_9)': { name: ')', title: 'DE_RPRN' },
  KC_LPRN: { name: ')', title: 'DE_RPRN' },
  'S(KC_0)': { name: '=', title: 'DE_EQL' },
  KC_RPRN: { name: '=', title: 'DE_EQL' },
  'S(KC_MINS)': { name: '?', title: 'DE_QUES' },
  KC_UNDS: { name: '?', title: 'DE_QUES' },
  'S(KC_EQL)': { name: '`', title: 'DE_GRV (dead)' },
  KC_PLUS: { name: '`', title: 'DE_GRV (dead)' },
  // Row 2
  'S(KC_RBRC)': { name: '*', title: 'DE_ASTR' },
  KC_RCBR: { name: '*', title: 'DE_ASTR' },
  // Row 3
  'S(KC_NUHS)': { name: "'", title: 'DE_QUOT' },
  // Row 4
  'S(KC_NUBS)': { name: '>', title: 'DE_RABK' },
  'S(KC_COMM)': { name: ';', title: 'DE_SCLN' },
  KC_LT: { name: ';', title: 'DE_SCLN' },
  'S(KC_DOT)': { name: ':', title: 'DE_COLN' },
  KC_GT: { name: ':', title: 'DE_COLN' },
  'S(KC_SLSH)': { name: '_', title: 'DE_UNDS' },
  KC_QUES: { name: '_', title: 'DE_UNDS' },

  /* AltGr symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │   │   │ ² │ ³ │   │   │   │ { │ [ │ ] │ } │ \ │   │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ @ │   │ € │   │   │   │   │   │   │   │   │ ~ │     │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┐    │
   * │      │   │   │   │   │   │   │   │   │   │   │   │   │    │
   * ├────┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴───┴────┤
   * │    │ | │   │   │   │   │   │   │ µ │   │   │   │          │
   * ├────┼───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'ALGR(KC_2)': { name: '²', title: 'DE_SUP2' },
  'ALGR(KC_3)': { name: '³', title: 'DE_SUP3' },
  'ALGR(KC_7)': { name: '{', title: 'DE_LCBR' },
  'ALGR(KC_8)': { name: '[', title: 'DE_LBRC' },
  'ALGR(KC_9)': { name: ']', title: 'DE_RBRC' },
  'ALGR(KC_0)': { name: '}', title: 'DE_RCBR' },
  'ALGR(KC_MINS)': { name: '\\', title: 'DE_BSLS' },
  // Row 2
  'ALGR(KC_Q)': { name: '@', title: 'DE_AT' },
  'ALGR(KC_E)': { name: '€', title: 'DE_EURO' },
  'ALGR(KC_RBRC)': { name: '~', title: 'DE_TILD' },
  // Row 4
  'ALGR(KC_NUBS)': { name: '|', title: 'DE_PIPE' },
  'ALGR(KC_M)': { name: 'µ', title: 'DE_MICR' },

  /* Other keys */
  KC_BSLS: { name: "'\n#", title: '' },
  'S(KC_BSLS)': { name: "'", title: '' },
  KC_LCBR: { name: 'Ü', title: 'S(DE_UDIA) (capital Ü)' },
  KC_COLN: { name: 'Ö', title: 'S(DE_ODIA) (capital Ö)' },
  KC_PIPE: { name: "'", title: 'DE_QUOT' },
  KC_DQUO: { name: 'Ä', title: 'S(DE_ADIA) (capital Ä)' },

  SC_LSPO: { name: 'LS / )', title: 'Left Shift when held, ) when tapped' },
  SC_RSPC: { name: 'RS / =', title: 'Right Shift when held, = when tapped' },
  SC_LCPO: { name: 'LC / )', title: 'Left Control when held, ) when tapped' },
  SC_RCPC: { name: 'RC / =', title: 'Right Control when held, = when tapped' },
  SC_LAPO: { name: 'LA / )', title: 'Left Alt when held, ) when tapped' },
  SC_RAPC: { name: 'RA / =', title: 'Right Alt when held, = when tapped' },

  QK_GESC: {
    name: '^/°\nEsc',
    title: 'Esc normally, but ^ when GUI is active or ° when Shift is active'
  },

  KC_LCTL: { name: 'Left Strg' },
  KC_RCTL: { name: 'Right Strg' }
};
