/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ F │ P │ G │ J │ L │ U │ Y │ ; │ [ │ ] │  \  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │ A │ R │ S │ T │ D │ H │ N │ E │ I │ O │ ' │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │ Z │ X │ C │ V │ B │ K │ M │ , │ . │ / │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '~\n`', title: 'CM_GRV' },
  KC_1: { name: '!\n1', title: 'CM_1' },
  KC_2: { name: '@\n2', title: 'CM_2' },
  KC_3: { name: '#\n3', title: 'CM_3' },
  KC_4: { name: '$\n4', title: 'CM_4' },
  KC_5: { name: '%\n5', title: 'CM_5' },
  KC_6: { name: '^\n6', title: 'CM_6' },
  KC_7: { name: '&\n7', title: 'CM_7' },
  KC_8: { name: '*\n8', title: 'CM_8' },
  KC_9: { name: '(\n9', title: 'CM_9' },
  KC_0: { name: ')\n0', title: 'CM_0' },
  KC_MINS: { name: '_\n-', title: 'CM_MINS' },
  KC_EQL: { name: '+\n=', title: 'CM_EQL' },
  // Row 2
  KC_Q: { name: 'Q', title: 'CM_Q' },
  KC_W: { name: 'W', title: 'CM_W' },
  KC_E: { name: 'F', title: 'CM_F' },
  KC_R: { name: 'P', title: 'CM_P' },
  KC_T: { name: 'G', title: 'CM_G' },
  KC_Y: { name: 'J', title: 'CM_J' },
  KC_U: { name: 'L', title: 'CM_L' },
  KC_I: { name: 'U', title: 'CM_U' },
  KC_O: { name: 'Y', title: 'CM_Y' },
  KC_P: { name: ':\n;', title: 'CM_SCLN' },
  KC_LBRC: { name: '{\n[', title: 'CM_LBRC' },
  KC_RBRC: { name: '}\n]', title: 'CM_RBRC' },
  KC_BSLS: { name: '|\n\\', title: 'CM_BSLS' },
  // Row 3
  KC_A: { name: 'A', title: 'CM_A' },
  KC_S: { name: 'R', title: 'CM_R' },
  KC_D: { name: 'S', title: 'CM_S' },
  KC_F: { name: 'T', title: 'CM_T' },
  KC_G: { name: 'D', title: 'CM_D' },
  KC_H: { name: 'H', title: 'CM_H' },
  KC_J: { name: 'N', title: 'CM_N' },
  KC_K: { name: 'E', title: 'CM_E' },
  KC_L: { name: 'I', title: 'CM_I' },
  KC_SCLN: { name: 'O', title: 'CM_O' },
  KC_QUOT: { name: '"\n\'', title: 'CM_QUOT' },
  // Row 4
  KC_Z: { name: 'Z', title: 'CM_Z' },
  KC_X: { name: 'X', title: 'CM_X' },
  KC_C: { name: 'C', title: 'CM_C' },
  KC_V: { name: 'V', title: 'CM_V' },
  KC_B: { name: 'B', title: 'CM_B' },
  KC_N: { name: 'K', title: 'CM_K' },
  KC_M: { name: 'M', title: 'CM_M' },
  KC_COMM: { name: '<\n,', title: 'CM_COMM' },
  KC_DOT: { name: '>\n.', title: 'CM_DOT' },
  KC_SLSH: { name: '?\n/', title: 'CM_SLSH' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │ ! │ @ │ # │ $ │ % │ ^ │ & │ * │ ( │ ) │ _ │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │ : │ { │ } │  |  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │   │   │   │   │   │   │   │   │   │   │ " │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │   │   │   │   │   │   │   │ < │ > │ ? │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', title: 'CM_TILD' },
  KC_TILD: { name: '~', title: 'CM_TILD' },
  'S(KC_1)': { name: '!', title: 'CM_EXLM' },
  KC_EXLM: { name: '!', title: 'CM_EXLM' },
  'S(KC_2)': { name: '@', title: 'CM_AT' },
  KC_AT: { name: '@', title: 'CM_AT' },
  'S(KC_3)': { name: '#', title: 'CM_HASH' },
  KC_HASH: { name: '#', title: 'CM_HASH' },
  'S(KC_4)': { name: '$', title: 'CM_DLR' },
  KC_DLR: { name: '$', title: 'CM_DLR' },
  'S(KC_5)': { name: '%', title: 'CM_PERC' },
  KC_PERC: { name: '%', title: 'CM_PERC' },
  'S(KC_6)': { name: '^', title: 'CM_CIRC' },
  KC_CIRC: { name: '^', title: 'CM_CIRC' },
  'S(KC_7)': { name: '&', title: 'CM_AMPR' },
  KC_AMPR: { name: '&', title: 'CM_AMPR' },
  'S(KC_8)': { name: '*', title: 'CM_ASTR' },
  KC_ASTR: { name: '*', title: 'CM_ASTR' },
  'S(KC_9)': { name: '(', title: 'CM_LPRN' },
  KC_LPRN: { name: '(', title: 'CM_LPRN' },
  'S(KC_0)': { name: ')', title: 'CM_RPRN' },
  KC_RPRN: { name: ')', title: 'CM_RPRN' },
  'S(KC_MINS)': { name: '_', title: 'CM_UNDS' },
  KC_UNDS: { name: '_', title: 'CM_UNDS' },
  'S(KC_EQL)': { name: '+', title: 'CM_PLUS' },
  KC_PLUS: { name: '+', title: 'CM_PLUS' },
  // Row 2
  'S(KC_P)': { name: ':', title: 'CM_COLN' },
  'S(KC_LBRC)': { name: '{', title: 'CM_LCBR' },
  KC_LCBR: { name: '{', title: 'CM_LCBR' },
  'S(KC_RBRC)': { name: '}', title: 'CM_RCBR' },
  KC_RCBR: { name: '}', title: 'CM_RCBR' },
  'S(KC_BSLS)': { name: '|', title: 'CM_PIPE' },
  KC_PIPE: { name: '|', title: 'CM_PIPE' },
  // Row 3
  'S(KC_QUOT)': { name: '"', title: 'CM_DQUO' },
  KC_DQUO: { name: '"', title: 'CM_DQUO' },
  // Row 4
  'S(KC_COMM)': { name: '<', title: 'CM_LABK' },
  KC_LT: { name: '<', title: 'CM_LABK' },
  'S(KC_DOT)': { name: '>', title: 'CM_RABK' },
  KC_GT: { name: '>', title: 'CM_RABK' },
  'S(KC_SLSH)': { name: '?', title: 'CM_QUES' },
  KC_QUES: { name: '?', title: 'CM_QUES' },

  /* Other keys */
  KC_NUHS: { name: '|\n\\', title: '' },
  'S(KC_NUHS)': { name: '|', title: '' },
  KC_NUBS: { name: '|\n\\', title: '' },
  'S(KC_NUBS)': { name: '|', title: '' },
  KC_COLN: { name: 'O', title: 'S(CM_O) (capital O)' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: '`/~\nEsc',
    title: 'Esc normally, but ` when GUI is active or ~ when Shift is active'
  }
};
