/* Copyright 2022 - Generated by convert_keymap_extras_header.js
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

export default {
  /*
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ` │ 1 │ 2 │ 3 │ 4 │ 5 │ 6 │ 7 │ 8 │ 9 │ 0 │ - │ = │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │ Q │ W │ E │ R │ T │ Y │ U │ I │ O │ P │ [ │ ] │  \  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │ A │ S │ D │ F │ G │ H │ J │ K │ L │ ; │ ' │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │ Z │ X │ C │ V │ B │ N │ M │ , │ . │ / │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  KC_GRV: { name: '~\n`', title: '' },
  KC_1: { name: '!\n1', title: '' },
  KC_2: { name: '@\n2', title: '' },
  KC_3: { name: '#\n3', title: '' },
  KC_4: { name: '$\n4', title: '' },
  KC_5: { name: '%\n5', title: '' },
  KC_6: { name: '^\n6', title: '' },
  KC_7: { name: '&\n7', title: '' },
  KC_8: { name: '*\n8', title: '' },
  KC_9: { name: '(\n9', title: '' },
  KC_0: { name: ')\n0', title: '' },
  KC_MINS: { name: '_\n-', title: '' },
  KC_EQL: { name: '+\n=', title: '' },
  // Row 2
  KC_Q: { name: 'Q', title: '' },
  KC_W: { name: 'W', title: '' },
  KC_E: { name: 'E', title: '' },
  KC_R: { name: 'R', title: '' },
  KC_T: { name: 'T', title: '' },
  KC_Y: { name: 'Y', title: '' },
  KC_U: { name: 'U', title: '' },
  KC_I: { name: 'I', title: '' },
  KC_O: { name: 'O', title: '' },
  KC_P: { name: 'P', title: '' },
  KC_LBRC: { name: '{\n[', title: '' },
  KC_RBRC: { name: '}\n]', title: '' },
  KC_BSLS: { name: '|\n\\', title: '' },
  // Row 3
  KC_A: { name: 'A', title: '' },
  KC_S: { name: 'S', title: '' },
  KC_D: { name: 'D', title: '' },
  KC_F: { name: 'F', title: '' },
  KC_G: { name: 'G', title: '' },
  KC_H: { name: 'H', title: '' },
  KC_J: { name: 'J', title: '' },
  KC_K: { name: 'K', title: '' },
  KC_L: { name: 'L', title: '' },
  KC_SCLN: { name: ':\n;', title: '' },
  KC_QUOT: { name: '"\n\'', title: '' },
  // Row 4
  KC_Z: { name: 'Z', title: '' },
  KC_X: { name: 'X', title: '' },
  KC_C: { name: 'C', title: '' },
  KC_V: { name: 'V', title: '' },
  KC_B: { name: 'B', title: '' },
  KC_N: { name: 'N', title: '' },
  KC_M: { name: 'M', title: '' },
  KC_COMM: { name: '<\n,', title: '' },
  KC_DOT: { name: '>\n.', title: '' },
  KC_SLSH: { name: '?\n/', title: '' },

  /* Shifted symbols
   * ┌───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───┬───────┐
   * │ ~ │ ! │ @ │ # │ $ │ % │ ^ │ & │ * │ ( │ ) │ _ │ + │       │
   * ├───┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─────┤
   * │     │   │   │   │   │   │   │   │   │   │   │ { │ } │  |  │
   * ├─────┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴┬──┴─────┤
   * │      │   │   │   │   │   │   │   │   │   │ : │ " │        │
   * ├──────┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴─┬─┴────────┤
   * │        │   │   │   │   │   │   │   │ < │ > │ ? │          │
   * ├────┬───┴┬──┴─┬─┴───┴───┴───┴───┴───┴──┬┴───┼───┴┬────┬────┤
   * │    │    │    │                        │    │    │    │    │
   * └────┴────┴────┴────────────────────────┴────┴────┴────┴────┘
   */
  // Row 1
  'S(KC_GRV)': { name: '~', title: '' },
  KC_TILD: { name: '~', title: '' },
  'S(KC_1)': { name: '!', title: '' },
  KC_EXLM: { name: '!', title: '' },
  'S(KC_2)': { name: '@', title: '' },
  KC_AT: { name: '@', title: '' },
  'S(KC_3)': { name: '#', title: '' },
  KC_HASH: { name: '#', title: '' },
  'S(KC_4)': { name: '$', title: '' },
  KC_DLR: { name: '$', title: '' },
  'S(KC_5)': { name: '%', title: '' },
  KC_PERC: { name: '%', title: '' },
  'S(KC_6)': { name: '^', title: '' },
  KC_CIRC: { name: '^', title: '' },
  'S(KC_7)': { name: '&', title: '' },
  KC_AMPR: { name: '&', title: '' },
  'S(KC_8)': { name: '*', title: '' },
  KC_ASTR: { name: '*', title: '' },
  'S(KC_9)': { name: '(', title: '' },
  KC_LPRN: { name: '(', title: '' },
  'S(KC_0)': { name: ')', title: '' },
  KC_RPRN: { name: ')', title: '' },
  'S(KC_MINS)': { name: '_', title: '' },
  KC_UNDS: { name: '_', title: '' },
  'S(KC_EQL)': { name: '+', title: '' },
  KC_PLUS: { name: '+', title: '' },
  // Row 2
  'S(KC_LBRC)': { name: '{', title: '' },
  KC_LCBR: { name: '{', title: '' },
  'S(KC_RBRC)': { name: '}', title: '' },
  KC_RCBR: { name: '}', title: '' },
  'S(KC_BSLS)': { name: '|', title: '' },
  KC_PIPE: { name: '|', title: '' },
  // Row 3
  'S(KC_SCLN)': { name: ':', title: '' },
  KC_COLN: { name: ':', title: '' },
  'S(KC_QUOT)': { name: '"', title: '' },
  KC_DQUO: { name: '"', title: '' },
  // Row 4
  'S(KC_COMM)': { name: '<', title: '' },
  KC_LT: { name: '<', title: '' },
  'S(KC_DOT)': { name: '>', title: '' },
  KC_GT: { name: '>', title: '' },
  'S(KC_SLSH)': { name: '?', title: '' },
  KC_QUES: { name: '?', title: '' },

  /* Other keys */
  KC_NUHS: { name: '|\n\\', title: '' },
  'S(KC_NUHS)': { name: '|', title: '' },
  KC_NUBS: { name: '|\n\\', title: '' },
  'S(KC_NUBS)': { name: '|', title: '' },

  SC_LSPO: { name: 'LS / (', title: 'Left Shift when held, ( when tapped' },
  SC_RSPC: { name: 'RS / )', title: 'Right Shift when held, ) when tapped' },
  SC_LCPO: { name: 'LC / (', title: 'Left Control when held, ( when tapped' },
  SC_RCPC: { name: 'RC / )', title: 'Right Control when held, ) when tapped' },
  SC_LAPO: { name: 'LA / (', title: 'Left Alt when held, ( when tapped' },
  SC_RAPC: { name: 'RA / )', title: 'Right Alt when held, ) when tapped' },

  QK_GESC: {
    name: '`/~\nEsc',
    title: 'Esc normally, but ` when GUI is active or ~ when Shift is active'
  }
};
