export default [
  { label: 'ISO/JIS', width: 'label', group: true },

  { name: 'Esc', code: 'KC_ESC', keys: 'esc', title: 'KC_ESC' },
  { width: 1000 },
  { name: 'F1', code: 'KC_F1', title: 'KC_F1' },
  { name: 'F2', code: 'KC_F2', title: 'KC_F2' },
  { name: 'F3', code: 'KC_F3', title: 'KC_F3' },
  { name: 'F4', code: 'KC_F4', title: 'KC_F4' },
  { width: 500 },
  { name: 'F5', code: 'KC_F5', title: 'KC_F5' },
  { name: 'F6', code: 'KC_F6', title: 'KC_F6' },
  { name: 'F7', code: 'KC_F7', title: 'KC_F7' },
  { name: 'F8', code: 'KC_F8', title: 'KC_F8' },
  { width: 500 },
  { name: 'F9', code: 'KC_F9', title: 'KC_F9' },
  { name: 'F10', code: 'KC_F10', title: 'KC_F10' },
  { name: 'F11', code: 'KC_F11', title: 'KC_F11' },
  { name: 'F12', code: 'KC_F12', title: 'KC_F12' },
  { width: 250 },
  { name: 'Print Screen', code: 'KC_PSCR', title: 'KC_PSCR' },
  { name: 'Scroll Lock', code: 'KC_SLCK', title: 'KC_SLCK' },
  { name: 'Pause', code: 'KC_PAUS', title: 'KC_PAUS' },
  { width: 0 },

  { name: '¬\n`', code: 'KC_GRV', keys: '`', title: 'KC_GRV' },
  { name: '!\n1', code: 'KC_1', keys: '1', title: 'KC_1' },
  { name: '"\n2', code: 'KC_2', keys: '2', title: 'KC_2' },
  { name: '£\n3', code: 'KC_3', keys: '3', title: 'KC_3' },
  { name: '$\n4', code: 'KC_4', keys: '4', title: 'KC_4' },
  { name: '%\n5', code: 'KC_5', keys: '5', title: 'KC_5' },
  { name: '^\n6', code: 'KC_6', keys: '6', title: 'KC_6' },
  { name: '&\n7', code: 'KC_7', keys: '7', title: 'KC_7' },
  { name: '*\n8', code: 'KC_8', keys: '8', title: 'KC_8' },
  { name: '(\n9', code: 'KC_9', keys: '9', title: 'KC_9' },
  { name: ')\n0', code: 'KC_0', keys: '0', title: 'KC_0' },
  { name: '_\n-', code: 'KC_MINS', keys: '-', title: 'KC_MINS' },
  { name: '+\n=', code: 'KC_EQL', keys: '=', title: 'KC_EQL' },
  { name: '|\n¥', code: 'KC_JYEN', title: 'KC_JYEN - JIS Yen and |' },
  {
    name: 'Back Space',
    code: 'KC_BSPC',
    keys: 'backspace',
    title: 'KC_BSPC'
  },
  { width: 250 },
  { name: 'Insert', code: 'KC_INS', keys: 'insert', title: 'KC_INS' },
  { name: 'Home', code: 'KC_HOME', keys: 'home', title: 'KC_HOME' },
  { name: 'Page Up', code: 'KC_PGUP', keys: 'pageup', title: 'KC_PGUP' },
  { width: 250 },
  { name: 'Num Lock', code: 'KC_NLCK', keys: 'num', title: 'KC_NLCK' },
  { name: '/', code: 'KC_PSLS', keys: 'num_divide', title: 'KC_PSLS' },
  { name: '*', code: 'KC_PAST', keys: 'num_multiply', title: 'KC_PAST' },
  { name: '-', code: 'KC_PMNS', keys: 'num_subtract', title: 'KC_PMNS' },
  { width: 0 },

  { name: 'Tab', code: 'KC_TAB', keys: 'tab', title: 'KC_TAB', width: 1500 },
  { name: 'q', code: 'KC_Q', keys: 'q', title: 'KC_Q' },
  { name: 'w', code: 'KC_W', keys: 'w', title: 'KC_W' },
  { name: 'e', code: 'KC_E', keys: 'e', title: 'KC_E' },
  { name: 'r', code: 'KC_R', keys: 'r', title: 'KC_R' },
  { name: 't', code: 'KC_T', keys: 't', title: 'KC_T' },
  { name: 'y', code: 'KC_Y', keys: 'y', title: 'KC_Y' },
  { name: 'u', code: 'KC_U', keys: 'u', title: 'KC_U' },
  { name: 'i', code: 'KC_I', keys: 'i', title: 'KC_I' },
  { name: 'o', code: 'KC_O', keys: 'o', title: 'KC_O' },
  { name: 'p', code: 'KC_P', keys: 'p', title: 'KC_P' },
  { name: '{\n[', code: 'KC_LBRC', keys: '[', title: 'KC_LBRC' },
  { name: '}\n]', code: 'KC_RBRC', keys: ']', title: 'KC_RBRC' },
  { width: 1500 },
  { width: 250 },
  { name: 'Del', code: 'KC_DEL', keys: 'delete', title: 'KC_DEL' },
  { name: 'End', code: 'KC_END', keys: 'end', title: 'KC_END' },
  { name: 'Page Down', code: 'KC_PGDN', keys: 'pagedown', title: 'KC_PGDN' },
  { width: 250 },
  { name: '7', code: 'KC_P7', keys: 'num_7', title: 'KC_P7' },
  { name: '8', code: 'KC_P8', keys: 'num_8', title: 'KC_P8' },
  { name: '9', code: 'KC_P9', keys: 'num_9', title: 'KC_P9' },
  { name: '+', code: 'KC_PPLS', keys: 'num_add', title: 'KC_PPLS' },
  { width: 0 },

  {
    name: 'Caps Lock',
    code: 'KC_CAPS',
    keys: 'caps_lock',
    title: 'KC_CAPS',
    width: 1750
  },
  { name: 'a', code: 'KC_A', keys: 'a', title: 'KC_A' },
  { name: 's', code: 'KC_S', keys: 's', title: 'KC_S' },
  { name: 'd', code: 'KC_D', keys: 'd', title: 'KC_D' },
  { name: 'f', code: 'KC_F', keys: 'f', title: 'KC_F' },
  { name: 'g', code: 'KC_G', keys: 'g', title: 'KC_G' },
  { name: 'h', code: 'KC_H', keys: 'h', title: 'KC_H' },
  { name: 'j', code: 'KC_J', keys: 'j', title: 'KC_J' },
  { name: 'k', code: 'KC_K', keys: 'k', title: 'KC_K' },
  { name: 'l', code: 'KC_L', keys: 'l', title: 'KC_L' },
  { name: ':\n;', code: 'KC_SCLN', keys: ';', title: 'KC_SCLN' },
  { name: "@\n'", code: 'KC_QUOT', keys: "'", title: 'KC_QUOT' },
  { name: '~\n#', code: 'KC_NUHS', title: 'KC_NUHS - Non-US # and ~' },
  { width: 1250 },
  {
    name: 'Enter',
    code: 'KC_ENT',
    keys: 'enter',
    classes: 'isoenter',
    width: 1250,
    title: 'KC_ENT'
  },
  { width: 3500 },
  { name: '4', code: 'KC_P4', keys: 'num_4', title: 'KC_P4' },
  { name: '5', code: 'KC_P5', keys: 'num_5', title: 'KC_P5' },
  { name: '6', code: 'KC_P6', keys: 'num_6', title: 'KC_P6' },
  { name: ',', code: 'KC_PCMM', title: 'KC_PCMM' },
  { width: 0 },

  {
    name: 'Left Shift',
    code: 'KC_LSFT',
    keys: 'shift',
    title: 'KC_LSFT',
    width: 1250
  },
  { name: '|\n\\', code: 'KC_NUBS', title: 'KC_NUBS - Non-US \\ and |' },
  { name: 'z', code: 'KC_Z', keys: 'z', title: 'KC_Z' },
  { name: 'x', code: 'KC_X', keys: 'x', title: 'KC_X' },
  { name: 'c', code: 'KC_C', keys: 'c', title: 'KC_C' },
  { name: 'v', code: 'KC_V', keys: 'v', title: 'KC_V' },
  { name: 'b', code: 'KC_B', keys: 'b', title: 'KC_B' },
  { name: 'n', code: 'KC_N', keys: 'n', title: 'KC_N' },
  { name: 'm', code: 'KC_M', keys: 'm', title: 'KC_M' },
  { name: '<\n,', code: 'KC_COMM', keys: ',', title: 'KC_COMM' },
  { name: '>\n.', code: 'KC_DOT', keys: '.', title: 'KC_DOT' },
  { name: '?\n/', code: 'KC_SLSH', keys: '/', title: 'KC_SLSH' },
  { name: '_\n\\', code: 'KC_RO', title: 'KC_RO - JIS \\ and _' },
  { name: 'Right Shift', code: 'KC_RSFT', title: 'KC_RSFT', width: 1750 },
  { width: 1250 },
  { name: 'Up', code: 'KC_UP', keys: 'up', title: 'KC_UP' },
  { width: 1250 },
  { name: '1', code: 'KC_P1', keys: 'num_1', title: 'KC_P1' },
  { name: '2', code: 'KC_P2', keys: 'num_2', title: 'KC_P2' },
  { name: '3', code: 'KC_P3', keys: 'num_3', title: 'KC_P3' },
  { name: '=', code: 'KC_PEQL', title: 'KC_PEQL' },
  { width: 0 },

  {
    name: 'Left Ctrl',
    code: 'KC_LCTL',
    keys: 'ctrl',
    title: 'KC_LCTL',
    width: 1250
  },
  {
    name: 'Left OS',
    code: 'KC_LGUI',
    keys: 'cmd',
    title: 'KC_LGUI',
    width: 1250
  },
  {
    name: 'Left Alt',
    code: 'KC_LALT',
    keys: 'alt',
    title: 'KC_LALT',
    width: 1250
  },
  {
    name: '無変換',
    code: 'KC_MHEN',
    title: 'KC_MHEN - JIS Muhenkan',
    width: 1250
  },
  {
    name: 'Space',
    code: 'KC_SPC',
    keys: 'space',
    title: 'KC_SPC',
    width: 4000
  },
  {
    name: '変換',
    code: 'KC_HENK',
    title: 'KC_HENK - JIS Henkan',
    width: 1250
  },
  {
    name: 'かな',
    code: 'KC_KANA',
    title: 'KC_KANA - JIS Katakana/Hiragana',
    width: 1250
  },
  { name: 'Right OS', code: 'KC_RGUI', title: 'KC_RGUI', width: 1250 },
  { name: 'Menu', code: 'KC_APP', title: 'KC_APP' },
  { name: 'Right Ctrl', code: 'KC_RCTL', title: 'KC_RCTL', width: 1250 },
  { width: 250 },
  { name: 'Left', code: 'KC_LEFT', keys: 'left', title: 'KC_LEFT' },
  { name: 'Down', code: 'KC_DOWN', keys: 'down', title: 'KC_DOWN' },
  { name: 'Right', code: 'KC_RGHT', keys: 'right', title: 'KC_RGHT' },
  { width: 250 },
  { name: '0', code: 'KC_P0', keys: 'num_0', title: 'KC_P0', width: 2000 },
  { name: '.', code: 'KC_PDOT', keys: 'num_decimal', title: 'KC_PDOT' },
  { name: 'Enter', code: 'KC_PENT', keys: 'num_enter', title: 'KC_PENT' },

  { label: 'Korean and Chinese', width: 'label' },

  { name: '漢字', code: 'KC_HANJ', title: 'KC_HANJ - Korean Hanja' },
  { name: '한영', code: 'KC_HAEN', title: 'KC_HAEN - Korean Han/Yeong' },

  { label: 'Shifted symbols', width: 'label' },

  { name: '~', code: 'KC_TILD', keys: '`', title: 'KC_TILD' },
  { name: '!', code: 'KC_EXLM', keys: '!', title: 'KC_EXLM' },
  { name: '@', code: 'KC_AT', keys: '@', title: 'KC_AT' },
  { name: '#', code: 'KC_HASH', keys: '#', title: 'KC_HASH' },
  { name: '$', code: 'KC_DLR', keys: '$', title: 'KC_DLR' },
  { name: '%', code: 'KC_PERC', keys: '%', title: 'KC_PERC' },
  { name: '^', code: 'KC_CIRC', keys: '^', title: 'KC_CIRC' },
  { name: '&', code: 'KC_AMPR', keys: '&', title: 'KC_AMPR' },
  { name: '*', code: 'KC_ASTR', keys: '*', title: 'KC_ASTR' },
  { name: '(', code: 'KC_LPRN', keys: '(', title: 'KC_LPRN' },
  { name: ')', code: 'KC_RPRN', keys: ')', title: 'KC_RPRN' },
  { name: '_', code: 'KC_UNDS', keys: '_', title: 'KC_UNDS' },
  { name: '+', code: 'KC_PLUS', keys: '+', title: 'KC_PLUS' },
  { name: '{', code: 'KC_LCBR', keys: '{', title: 'KC_LCBR' },
  { name: '}', code: 'KC_RCBR', keys: '}', title: 'KC_RCBR' },
  { name: '<', code: 'KC_LT', keys: '<', title: 'KC_LT' },
  { name: '>', code: 'KC_GT', keys: '>', title: 'KC_GT' },
  { name: ':', code: 'KC_COLN', keys: ':', title: 'KC_COLN' },
  { name: '|', code: 'KC_PIPE', keys: '|', title: 'KC_PIPE' },
  { name: '?', code: 'KC_QUES', keys: '?', title: 'KC_QUES' },
  { name: '"', code: 'KC_DQUO', keys: '"', title: 'KC_DQUO' }
];
