export default {
  name: 'mt3-susuwatari-ortho',
  override: {
    KC_ENT: 'accent',
    KC_ESC: 'accent',
    QK_GESC: 'accent',
    KC_DEL: 'mod',
    KC_QUOT: 'mod',
    KC_GRV: 'mod',
    KC_LALT: 'mod-blue',
    KC_RALT: 'mod-blue',
    KC_LGUI: 'mod-blue',
    KC_RGUI: 'mod-blue',
    KC_RCTL: 'mod-blue',
    KC_LCTL: 'mod-blue',
    KC_APP: 'mod-blue',
    KC_UP: 'mod-blue',
    KC_LEFT: 'mod-blue',
    KC_DOWN: 'mod-blue',
    KC_RGHT: 'mod-blue',
    KC_MENU: 'mod-blue',
    BL_STEP: 'mod-blue',
    'MO(layer)': 'mod-blue',
    'TG(layer)': 'mod-blue',
    'TO(layer)': 'mod-blue',
    'TT(layer)': 'mod-blue',
    'DF(layer)': 'mod-blue',
    'OSL(layer)': 'mod-blue',
    SC_RSPC: 'mod',
    SC_LSPO: 'mod'
  }
};
