export default [
  { label: 'ANSI', width: 'label', group: true },

  { name: 'Esc', code: 'KC_ESC', keys: 'esc' },
  { width: 1000 },
  { name: 'F1', code: 'KC_F1', keys: 'f1' },
  { name: 'F2', code: 'KC_F2', keys: 'f2' },
  { name: 'F3', code: 'KC_F3', keys: 'f3' },
  { name: 'F4', code: 'KC_F4', keys: 'f4' },
  { width: 500 },
  { name: 'F5', code: 'KC_F5', keys: 'f5' },
  { name: 'F6', code: 'KC_F6', keys: 'f6' },
  { name: 'F7', code: 'KC_F7', keys: 'f7' },
  { name: 'F8', code: 'KC_F8', keys: 'f8' },
  { width: 500 },
  { name: 'F9', code: 'KC_F9', keys: 'f9' },
  { name: 'F10', code: 'KC_F10', keys: 'f10' },
  { name: 'F11', code: 'KC_F11', keys: 'f11' },
  { name: 'F12', code: 'KC_F12', keys: 'f12' },
  { width: 250 },
  { name: 'Print Screen', code: 'KC_PSCR' },
  { name: 'Scroll Lock', code: 'KC_SCRL' },
  { name: 'Pause', code: 'KC_PAUS' },
  { width: 0 },

  { name: '~\n`', code: 'KC_GRV', keys: '`' },
  { name: '!\n1', code: 'KC_1', keys: '1' },
  { name: '@\n2', code: 'KC_2', keys: '2' },
  { name: '#\n3', code: 'KC_3', keys: '3' },
  { name: '$\n4', code: 'KC_4', keys: '4' },
  { name: '%\n5', code: 'KC_5', keys: '5' },
  { name: '^\n6', code: 'KC_6', keys: '6' },
  { name: '&\n7', code: 'KC_7', keys: '7' },
  { name: '*\n8', code: 'KC_8', keys: '8' },
  { name: '(\n9', code: 'KC_9', keys: '9' },
  { name: ')\n0', code: 'KC_0', keys: '0' },
  { name: '_\n-', code: 'KC_MINS', keys: '-' },
  { name: '+\n=', code: 'KC_EQL', keys: '=' },
  { name: 'Back Space', code: 'KC_BSPC', keys: 'backspace', width: 2000 },
  { width: 250 },
  { name: 'Insert', code: 'KC_INS', keys: 'insert' },
  { name: 'Home', code: 'KC_HOME', keys: 'home' },
  { name: 'Page Up', code: 'KC_PGUP', keys: 'pageup' },
  { width: 250 },
  { name: 'Num Lock', code: 'KC_NUM', keys: 'num' },
  { name: '/', code: 'KC_PSLS', keys: 'num_divide' },
  { name: '*', code: 'KC_PAST', keys: 'num_multiply' },
  { name: '-', code: 'KC_PMNS', keys: 'num_subtract' },
  { width: 0 },

  { name: 'Tab', code: 'KC_TAB', keys: 'tab', width: 1500 },
  { name: 'q', code: 'KC_Q', keys: 'q' },
  { name: 'w', code: 'KC_W', keys: 'w' },
  { name: 'e', code: 'KC_E', keys: 'e' },
  { name: 'r', code: 'KC_R', keys: 'r' },
  { name: 't', code: 'KC_T', keys: 't' },
  { name: 'y', code: 'KC_Y', keys: 'y' },
  { name: 'u', code: 'KC_U', keys: 'u' },
  { name: 'i', code: 'KC_I', keys: 'i' },
  { name: 'o', code: 'KC_O', keys: 'o' },
  { name: 'p', code: 'KC_P', keys: 'p' },
  { name: '{\n[', code: 'KC_LBRC', keys: '[' },
  { name: '}\n]', code: 'KC_RBRC', keys: ']' },
  { name: '|\n\\', code: 'KC_BSLS', keys: '\\', width: 1500 },
  { width: 250 },
  { name: 'Delete', code: 'KC_DEL', keys: 'delete' },
  { name: 'End', code: 'KC_END', keys: 'end' },
  { name: 'Page Down', code: 'KC_PGDN', keys: 'pagedown' },
  { width: 250 },
  { name: '7\nHome', code: 'KC_P7', keys: 'num_7' },
  { name: '8\n⏶', code: 'KC_P8', keys: 'num_8' },
  { name: '9\nPgUp', code: 'KC_P9', keys: 'num_9' },
  { name: '+', code: 'KC_PPLS', keys: 'num_add' },
  { width: 0 },

  { name: 'Caps Lock', code: 'KC_CAPS', keys: 'caps_lock', width: 1750 },
  { name: 'a', code: 'KC_A', keys: 'a' },
  { name: 's', code: 'KC_S', keys: 's' },
  { name: 'd', code: 'KC_D', keys: 'd' },
  { name: 'f', code: 'KC_F', keys: 'f' },
  { name: 'g', code: 'KC_G', keys: 'g' },
  { name: 'h', code: 'KC_H', keys: 'h' },
  { name: 'j', code: 'KC_J', keys: 'j' },
  { name: 'k', code: 'KC_K', keys: 'k' },
  { name: 'l', code: 'KC_L', keys: 'l' },
  { name: ':\n;', code: 'KC_SCLN', keys: ';' },
  { name: '"\n\'', code: 'KC_QUOT', keys: "'" },
  { name: 'Enter\n↵', code: 'KC_ENT', keys: 'enter', width: 2250 },
  { width: 3500 },
  { name: '4\n⏴', code: 'KC_P4', keys: 'num_4' },
  { name: '5', code: 'KC_P5', keys: 'num_5' },
  { name: '6\n⏵', code: 'KC_P6', keys: 'num_6' },
  { name: ',', code: 'KC_PCMM' },
  { width: 0 },

  { name: 'Left Shift', code: 'KC_LSFT', keys: 'shift', width: 2250 },
  { name: 'z', code: 'KC_Z', keys: 'z' },
  { name: 'x', code: 'KC_X', keys: 'x' },
  { name: 'c', code: 'KC_C', keys: 'c' },
  { name: 'v', code: 'KC_V', keys: 'v' },
  { name: 'b', code: 'KC_B', keys: 'b' },
  { name: 'n', code: 'KC_N', keys: 'n' },
  { name: 'm', code: 'KC_M', keys: 'm' },
  { name: '<\n,', code: 'KC_COMM', keys: ',' },
  { name: '>\n.', code: 'KC_DOT', keys: '.' },
  { name: '?\n/', code: 'KC_SLSH', keys: '/' },
  { name: 'Right Shift', code: 'KC_RSFT', width: 2750 },
  { width: 1250 },
  { name: '⏶', code: 'KC_UP', keys: 'up' },
  { width: 1250 },
  { name: '1\nEnd', code: 'KC_P1', keys: 'num_1' },
  { name: '2\n⏷', code: 'KC_P2', keys: 'num_2' },
  { name: '3\nPgDn', code: 'KC_P3', keys: 'num_3' },
  { name: '=', code: 'KC_PEQL' },
  { width: 0 },

  { name: 'Left Ctrl', code: 'KC_LCTL', keys: 'ctrl', width: 1250 },
  { name: 'Left GUI', code: 'KC_LGUI', keys: 'cmd', width: 1250 },
  { name: 'Left Alt', code: 'KC_LALT', keys: 'alt', width: 1250 },
  { name: 'Space', code: 'KC_SPC', keys: 'space', width: 6250 },
  { name: 'Right Alt', code: 'KC_RALT', width: 1250 },
  { name: 'Right GUI', code: 'KC_RGUI', width: 1250 },
  { name: '≡', code: 'KC_APP', title: 'Context Menu', width: 1250 },
  { name: 'Right Ctrl', code: 'KC_RCTL', width: 1250 },
  { width: 250 },
  { name: '⏴', code: 'KC_LEFT', keys: 'left' },
  { name: '⏷', code: 'KC_DOWN', keys: 'down' },
  { name: '⏵', code: 'KC_RGHT', keys: 'right' },
  { width: 250 },
  { name: '0\nIns', code: 'KC_P0', keys: 'num_0', width: 2000 },
  { name: '.\nDel', code: 'KC_PDOT', keys: 'num_decimal' },
  { name: 'Enter', code: 'KC_PENT', keys: 'num_enter' },

  { label: 'Shifted symbols', width: 'label' },

  { name: '~', code: 'KC_TILD', keys: '~' },
  { name: '!', code: 'KC_EXLM', keys: '!' },
  { name: '@', code: 'KC_AT', keys: '@' },
  { name: '#', code: 'KC_HASH', keys: '#' },
  { name: '$', code: 'KC_DLR', keys: '$' },
  { name: '%', code: 'KC_PERC', keys: '%' },
  { name: '^', code: 'KC_CIRC', keys: '^' },
  { name: '&', code: 'KC_AMPR', keys: '&' },
  { name: '*', code: 'KC_ASTR', keys: '*' },
  { name: '(', code: 'KC_LPRN', keys: '(' },
  { name: ')', code: 'KC_RPRN', keys: ')' },
  { name: '_', code: 'KC_UNDS', keys: '_' },
  { name: '+', code: 'KC_PLUS', keys: '+' },
  { name: '{', code: 'KC_LCBR', keys: '{' },
  { name: '}', code: 'KC_RCBR', keys: '}' },
  { name: '<', code: 'KC_LT', keys: '<' },
  { name: '>', code: 'KC_GT', keys: '>' },
  { name: ':', code: 'KC_COLN', keys: ':' },
  { name: '|', code: 'KC_PIPE', keys: '|' },
  { name: '?', code: 'KC_QUES', keys: '?' },
  { name: '"', code: 'KC_DQUO', keys: '"' }
];
